### ISSUE TITLE
app is not compatible with ios14beta4

### ISSUE THREAD

**Issue by desmond-wang** [cds-snc/covid-alert-app#1001]
The ios14beta4 is available with exposure notifications available, however it requires `ENDeveloperRegion` and `ENAPIVersion`
The link: [Apple COVID-19 guide ](https://developer.apple.com/documentation/exposurenotification) 
Otherwise, it just shows <no loc> error under settings-Exposure notification-Exposure logging-exposure checks. 
![F14E7781-D3DE-45FE-9C52-EEB009856AE5](https://user-images.githubusercontent.com/19340532/89438515-ea659680-d716-11ea-9357-f472adf51701.png)

_Originally posted by @desmond-wang in https://github.com/cds-snc/covid-alert-app/issues/981#issuecomment-669294801_

**Comment by timarney** [comment]
Thanks @desmond-wang this has been added to our backlog.

**Comment by desmond-wang** [comment]
It only need to add two lines. Hope you guys could support it ASAP. Thank you. 

I also wondering for the exposure time(currently >15 mins). I am thinking about some scenario like small talk with stranger in the elevator or buses platforms which is less than 15 mins. If two people met within 2 metres for more than 15 mins, it is usually friends which we will know if they have been diagnosed the COVID-19 virus.

**Comment by lexcyn** [comment]
I just e-mailed about this issue so please ignore, I also reported it. Might want to update the CDS help website with this information. As of right now it says the app is compatible with iOS 14 beta. While technically it is compatible, it's not checking codes, which could lead some people to have a false sense of security.

**Comment by timarney** [comment]
Closing this - will keep https://github.com/cds-snc/covid-alert-app/issues/981 open .
