### ISSUE TITLE
Temporary disable for healthcare workers wearing PPE

### ISSUE THREAD

**Issue by colinbendell** [cds-snc/covid-alert-app#1020]
# Summary
The app needs a way to disable tracking for nurses and docs while wearing PPE (personal protective equipment)

# detail
Health care professionals need the benefits of the tracking app because the routinely come into contact with patients that don't have Covid and don't want to be a transmission vector. Yet in other situations these nurses and doctors will be wearing PPE during their shift. Any contact with Covid patients should not be tracked because they have taken the necessary precautions. Alerting these workers that they have been in contact with someone with Covid is not something they don't already know. What they need to know is if it was when they were not protected (off work) or not. 

For this reason the app needs a mechanism to temporarily disable tracking. This should be for a work shift duration (8 or 12h pause) or until a set time in the future. 

# Unresolved questions / Out of scope

Currently disabling the API in Apple forces a delete of all data. Pausing of the tracking should not delete data.

**Comment by timarney** [comment]
Thanks @colinbendell I have flagged this back to the team.

**Comment by colinbendell** [comment]
Thanks.

Talking with some old colleagues in both the Ontario and Nunavut health regions and there seems to be quite a bit of confusion on the applicability of the App for health region staff. This is a substantial number of users/citizens that should be considered as a key stakeholder for the app's success. IMHO Of Course

**Comment by emilykuret** [comment]
Thanks for the feedback. The feature has been added to the backlog and we will work to prioritize it.

**Comment by colinbendell** [comment]
Is there a public way to track the backlog? Could I suggest that we keep issues like this open until they are implemented as a means to keep the backlog public?

**Comment by colinbendell** [comment]
@emilykuret where can we see the backlog? The release notes, by way of cbc, indicate that this is soon to be released? [1] 

[1] https://www.cbc.ca/news/canada/london/health-canada-to-release-covid-alert-app-geared-to-health-care-workers-1.5806651

**Comment by timarney** [comment]
Hi @colinbendell 

The feature rolled out today.

https://twitter.com/CDS_GC/status/1337057419025854465
