### ISSUE TITLE
Licence text is only available in English

### ISSUE THREAD

**Issue by 123chess456** [cds-snc/covid-alert-app#1034]
# Summary

This app is currently licensed under the Apache License, which is only available in English with no French translation. Since COVID-Alert is the official contact tracing app for Canada, the app should be licensed under both an English and French licence so that Francophones are not unnecessarily disadvantaged when using the source code.

A potential replacement could be the Open Government Licence which the Government of Canada has developed to serve the needs of the public sector; it comes with both an English and French translation. Like the Apache License, it's a permissive licence that requires attribution and shouldn't substantially change the licensing conditions.

https://open.canada.ca/en/open-government-licence-canada

https://ouvert.canada.ca/fr/licence-du-gouvernement-ouvert-canada

Should reach out upstream and see if they would be amenable to relicensing under these conditions. The above also applies for other CDS repos.

**Comment by timarney** [comment]
@sboots @lchski any thoughts?

**Comment by CalvinRodo** [comment]
According to [official GoC guidance on publishing open source code](https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/open-source-software/guide-for-publishing-open-source-code.html#toc04) 

> When the project is ... [a] derivative [work] of existing open source software, it is highly recommended to use the license which is usually used by the community

So in this case we will not be applying a new licence to this code base. 

We also have a requirement to use an [Open Source Initiative approved licence](https://opensource.org/licenses) when applying a licence software, the OGL is unfortunately not an OSI approved licence. 

The OGL was also never meant to be applied to Source Code and is really meant for open data/information, I've personally received recommendations in the past to not use it for licensing Source Code for that very reason. Unfortunately I have no official policy instrument or guidance on why we should not be using the OGL for source code, personally I think is something the GoC should publish.

**Comment by sboots** [comment]
+1 to @CalvinRodo's response above. 

@123chess456 thanks for raising this all the same! Calvin and I are checking in with some other Government of Canada open source experts on this (it's come up as a discussion on some other past GC open source projects, but what Calvin described is the general consensus these days). If anything changes down the road in terms of recommended best practices for licenses and Official Languages, we'll make that change and let you know here!
