### ISSUE TITLE
Exposure checks stopped

### ISSUE THREAD

**Issue by jeffmaher** [cds-snc/covid-alert-app#1046]
# Summary

Exposure checks stopped after 1+ weeks of not opening the app.

# Steps to reproduce

1. Install the app from the Apple App Store
1. Go through onboarding, enabling exposure notifications and iOS notifications
1. Leave the app
1. Don't open the app for a week or two
1. Check the Exposure Checks log in iOS settings

## Expected:

One or more checks to have happened within the last week.

## Actual:

Checks halted after a few days of working normally. Screenshots from checks on Aug 13:

- [Screenshot for Phone 1](https://user-images.githubusercontent.com/950486/90184069-8d0abe80-dd82-11ea-93f1-1aa7514f5b1f.png)
- [Screenshot for Phone 2](https://user-images.githubusercontent.com/950486/90184162-af9cd780-dd82-11ea-9abb-81de52a01458.png)

# Environment

This was experienced on two phones.

## Phone 1:

- iPhone X
- iOS 13.6 most of the time, but upgraded today to iOS 13.6.1
- The phone is usually on the charger, often on WiFi. Sometimes it is in airplane mode with WiFi and Bluetooth still enabled
- Background App Refresh is set to WiFi only, with COVID Alert enabled

## Phone 2:

- iPhone 7
- iOS 13.6
- Phone is often charged and on WiFi, but may have hit low battery during the duration
- Background App Refresh is set to off

# Unresolved questions / Out of scope

- When opening the app, exposure checks resume ([screenshot, Phone 1](https://user-images.githubusercontent.com/950486/90191966-efb68700-dd8f-11ea-932a-4dd6e368f5bb.png)). Maybe this is from the app being de-prioritized to issue background checks after several days of inactivity?

**Comment by jeberhardt** [comment]
This could have something to do with it:
https://developer.apple.com/documentation/exposurenotification/enstatus/enstatuspaused

This `exposureNotificationStatus` value of `ENStatusPaused` was introduced in iOS 13.6, and is not handled in the function `getStatusWithResolver`.

https://github.com/cds-snc/covid-alert-app/blob/eb3968b67281e2e2a8cb716210b70bbf42d7c315/ios/CovidShield/ExposureNotification.m#L68

**Comment by transcendent** [comment]
Installed the app on August 14th, appears to have stopped checking on the 15th and didn't resume until I opened the app. Looks like the background task isn't firing. Phone usually on wifi, never got below 50% battery. Phone was turned off overnight.

![IMG_2742](https://user-images.githubusercontent.com/734888/90335172-da647700-dfa0-11ea-8bf8-7ad2ad509d2e.PNG)

**Comment by timarney** [comment]
Running my test on 13.6 since Aug 13th

Checks have been fine so far - phone has been plugged and unplugged (very low battery - still doing checks).

**Comment by jeffmaher** [comment]
Confirming that this is still happening on Phone 2 as originally reported, with the exception that it is now on iOS 13.6.1. Here are a few more screenshots of the exposure checks log and lack of a sysdiagnosis log (from the Apple profile we installed specifically on these devices).

- [Exposure Check Logs](https://user-images.githubusercontent.com/950486/92060918-020a5c00-ed63-11ea-8f7b-18bb3a78eeb9.png)
- [System Logs](https://user-images.githubusercontent.com/950486/92060917-ffa80200-ed62-11ea-9dbd-85635046e65c.png)

**Comment by jeffmaher** [comment]
Phone 1 is still working correctly after the initial bug, but turning off its background app updates at the iOS level to see if that replicates what's happening on Phone 2.

**Comment by timarney** [comment]
@jeffmaher closing this one - the team is looking into something similar outside of this we'll see what turns up.
