### ISSUE TITLE
Bug Getting notification not supported in this region - am in Ontario

### ISSUE THREAD

**Issue by lisafast** [cds-snc/covid-alert-app#1048]
# Summary

> I downloaded the app in Ontario. Selected Ontario as my province. Then went to Quebec to my cottage. Got the notification that it's not supported in this region - got it every day that I was there. OK. Because I can't turn the notifications OFF. Really wish I could turn the app off when I'm up there but fine, that's a different issue. Then came back to Ontario. And I'm still getting the notification. Every day. I've been in Ontario for 3 days now. It tells me to use settings to fix the province, but when I go into the app settings, it says I'm in Ontario. I've tried clicking Ontario again, still get notification next day. 

![Notifcation](https://user-images.githubusercontent.com/28159252/90191032-1c699f00-dd8e-11ea-96a6-ab2509edd45f.png)
![Settings-correct](https://user-images.githubusercontent.com/28159252/90191043-2390ad00-dd8e-11ea-9c37-549df3761313.png)

# Steps to reproduce

> I guess you would have to go to Quebec for a few days and then come back to Ontario to reproduce this bug. I note though that my husband @steve-h is not having this happen and he is on iOS 14. So maybe this is a temporary problem? 

# Environment

> iPhone 7 iOS 13.6

**Comment by timarney** [comment]
@emilykuret ☝️

**Comment by emilykuret** [comment]
Working with Apple on this issue - tracking these internally.

**Comment by emilykuret** [comment]
https://github.com/cds-snc/covid-alert-app/issues/977
