### ISSUE TITLE
Issue template(s)  - missing feature template

### ISSUE THREAD

**Issue by kbroughton** [cds-snc/covid-alert-app#1069]
# Summary | Résumé

Documentation bug.
On the top of the "issues" page: "If you have a bug or an **idea**, read the contributing guidelines before opening an issue."
However, clicking the link only offers security or bug categories.
Where is the right place to make feature suggestions?

# Steps to reproduce | Étapes à reproduire

Click the Issues tab

# Environment | Environnement logiciel

N/A

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

**Comment by timarney** [comment]
@jeffmaher ☝️
