### ISSUE TITLE
OS Level Exposure Notifications are misleading on iOS

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/covid-alert-app#1074]
# Summary | Résumé

Users are receiving the weekly OS-level exposure notifications that have a recap of the number of potential exposures they have had that week. These notifications are alarming and conflict with messaging in the app. The notifications don’t take into account the EN Framework configuration set by the app.

<img width="382" alt="Screen Shot 2020-08-20 at 2 35 23 PM" src="https://user-images.githubusercontent.com/5498428/90935709-0cbb0d80-e3c1-11ea-89ee-e02805548494.png">

# Steps to reproduce | Étapes à reproduire

1. Install the app on an iPhone
2. Expose your phone to a diagnosed phone for 1 minute at a distance of 5 metres.
3. Observe that the iPhone will not go into an exposed state, as expected
4. After a few days you will see a weekly, OS level notification that says you have "1 potential exposure".

# Environment | Environnement logiciel

iOS

**Comment by emilykuret** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Submit github issue for Apple OS Notifications](https://trello.com/c/rLN31AvD/409-submit-github-issue-for-apple-os-notifications)

**Comment by timarney** [comment]
https://twitter.com/ryancbriggs/status/1297176019728728065

**Comment by lepinsk** [comment]
Just ran into this myself; got a system-level "your device identified 1 potential exposure this week" notification on iOS, but the COVID Alert app says "No exposure detected".

Confusingly, tapping on the system notification brings you to "Exposure Notifications" in Settings.app.

What should be my (or any user's) interpretation of this? That iOS is naively listing *all* devices seen and the app is actually filtering by exposure time and distance? iOS also lets me export the exposure checks, which is equally opaque (but appears to show me 4 checks that turned up a match):

```json
{
      "Timestamp" : "2020-09-11 21:31:44 -0400",
      "Files" : [
        {
          "Hash" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          "MatchCount" : 1,
          "KeyCount" : 178,
          "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid",
          "Timestamp" : "2020-09-11 21:31:44 -0400"
        }
      ],
      "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid"
    },
    {
      "Timestamp" : "2020-09-11 21:31:44 -0400",
      "Files" : [
        {
          "Hash" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          "MatchCount" : 0,
          "KeyCount" : 10,
          "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid",
          "Timestamp" : "2020-09-11 21:31:44 -0400"
        }
      ],
      "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid"
    },
    {
      "Timestamp" : "2020-09-11 19:30:56 -0400",
      "Files" : [
        {
          "Hash" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          "MatchCount" : 1,
          "KeyCount" : 175,
          "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid",
          "Timestamp" : "2020-09-11 19:30:56 -0400"
        }
      ],
      "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid"
    },
    {
      "Timestamp" : "2020-09-11 17:30:57 -0400",
      "Files" : [
        {
          "Hash" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          "MatchCount" : 1,
          "KeyCount" : 162,
          "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid",
          "Timestamp" : "2020-09-11 17:30:57 -0400"
        }
      ],
      "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid"
    },
    {
      "Timestamp" : "2020-09-11 13:36:28 -0400",
      "Files" : [
        {
          "Hash" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          "MatchCount" : 1,
          "KeyCount" : 108,
          "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid",
          "Timestamp" : "2020-09-11 13:36:28 -0400"
        }
      ],
      "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid"
    },
```

Although, confusingly, two separate objects at `2020-09-11 21:31:44 -0400`, one of which has a positive `MatchCount` and one which doesn't.

**Comment by timarney** [comment]
Wording has been updated as seen here in iOS 14 (again this is at the OS level not via the app)

![Screen Shot 2020-09-23 at 8 38 35 PM](https://user-images.githubusercontent.com/62242/94087854-cf410a00-fddc-11ea-92ee-df33ac0dc6cf.png)

**Comment by timarney** [comment]
@lepinsk see https://github.com/cds-snc/covid-alert-app/issues/1163#issuecomment-702741221 for more information about MatchCount.

**Comment by timarney** [comment]
Closing this as the OS has now updated.
