### ISSUE TITLE
Quick button taps lead to a weird screen stack when navigating back

### ISSUE THREAD

**Issue by Gogo-ZvC** [cds-snc/covid-alert-app#1083]
# Summary | Résumé

A user is able to tap multiple buttons quickly, opening each corresponding screen and ultimately leading to a weird stack when navigating backwards. If they quickly tap button 1 (opens screen 1) and then button 2 (opens screen 2), both screens open and the user is left on screen 2, but when navigating back to the main menu, will have to go through screen 1.

![Multi-tap example](https://i.ibb.co/WFpzQSs/multi-tap-issue.gif)

# Steps to reproduce | Étapes à reproduire

**Note** 
- Most likely possible across the whole app, the steps below are for when the menu is available.

**Steps**
1. Tap to bring up the menu
2. Under Settings, quickly tap `Change province or territory` first then `Change language` second

**Expected**
- After tapping `Change province or territory` the user isn't able to tap another button until the action is finished
  - Main menu > Change province or territory screen

**Actual**
- After tapping `Change province or territory` the user is able to tap another button leading to a weird screen stack (refer to gif above)
  - Main menu > Change province or territory screen > Change language screen

# Environment | Environnement logiciel

- Android version 10
- OnePlus 7 Pro (GM1917) | Oxygen OS 10.3.4.GM21AA
- COVID Alert version 1.0.3

**Comment by timarney** [comment]
Closing this for now.  It's been added to our Trello inbox for further consideration / prioritization.
