### ISSUE TITLE
Narrow traceback duration

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-alert-app#1096]
aka "Traceback Duration"

Outcome: Only send exposures for dates that users are contagious.

As a user, I want to know if I have come in contact with someone who is contagious, so I can take the right precautions.

**Comment by amazingphilippe** [comment]
Link to Figma mockups: https://www.figma.com/file/0pLawavG1fnBTXSYn4pdKZ/Exposure-notification?node-id=10721%3A20478

Screenshots for reference. Refer to Figma to inspect designs.

![1 Default Menu](https://user-images.githubusercontent.com/5230720/91856051-0421cd00-ec34-11ea-9222-7f62a2b58e32.jpg)
![2 Steps](https://user-images.githubusercontent.com/5230720/91856057-06842700-ec34-11ea-98cd-c743b91e6c19.jpg)

Focused input + character chunking. Allow users to input chars and spaces. Allow pasting. Auto format if users do not enter the spaces.

![3 OTK input](https://user-images.githubusercontent.com/5230720/91856062-07b55400-ec34-11ea-8736-568ba634ed91.jpg)
![4 Radios](https://user-images.githubusercontent.com/5230720/91856063-084dea80-ec34-11ea-8620-a92547ee7939.jpg)
![5 Symptoms date](https://user-images.githubusercontent.com/5230720/91856064-08e68100-ec34-11ea-8350-3710d33c513f.jpg)
![6 Test dates](https://user-images.githubusercontent.com/5230720/91856065-097f1780-ec34-11ea-9012-891581dd1177.jpg)

Secondary button always goes back to step 2 (Radio screen)

![7 Confirmation](https://user-images.githubusercontent.com/5230720/91856068-0a17ae00-ec34-11ea-8652-d0b952405d2f.jpg)
![8 OS consent](https://user-images.githubusercontent.com/5230720/91856069-0a17ae00-ec34-11ea-8eae-b8bcb9d6d422.jpg)
![9 Errors](https://user-images.githubusercontent.com/5230720/91856070-0a17ae00-ec34-11ea-9d7c-da11cacb6c96.jpg)

**Comment by emilykuret** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement traceback duration](https://trello.com/c/x3COdM6o/486-implement-traceback-duration)

**Comment by timarney** [comment]
Based on the conversation from yesterday we've also moved the "prefer not to say" option out of the date picker.  It's now a button.

<img width="200" src="https://user-images.githubusercontent.com/62242/92920954-2a4c2780-f401-11ea-8dfd-68a1f037451b.jpg" />	<img width="200" src="https://user-images.githubusercontent.com/62242/92920881-038df100-f401-11ea-8c7f-50abc47a1804.jpg">

**Comment by timarney** [comment]
Noting:
Yesterday we added the radio buttons - we'll need to work on ensuring the are accessible (today).

<img width="300" src="https://user-images.githubusercontent.com/62242/92921216-a6df0600-f401-11ea-985a-a464c00b5fb5.jpg" />

**Comment by amazingphilippe** [comment]
> Might help with context for that button and draw attention to the text.

1. I brought this issue in a thread in the interaction design channel. The two buttons together reinforces the idea of having a choice. Also, by separating the buttons, people might skip reading below the primary button altogether. 
2. All good on the "Prefer not to say" button.
3. Make sure we have an empty option in the date-picker so we don't force a default date.

**Comment by amazingphilippe** [comment]
updating with content changes @timarney @smcmurtry 

View flow using the same link as before. Here are images for reference!

![1 Default Menu](https://user-images.githubusercontent.com/5230720/93128770-00636100-f69e-11ea-8f60-e1fd8d7175e7.jpg)
![2 Steps](https://user-images.githubusercontent.com/5230720/93128777-01948e00-f69e-11ea-8ae1-ad038e1a103f.jpg)
![3 OTK input](https://user-images.githubusercontent.com/5230720/93128779-022d2480-f69e-11ea-84b2-95291d8a5302.jpg)
![4 Radios](https://user-images.githubusercontent.com/5230720/93128782-022d2480-f69e-11ea-9184-d8e795c958df.jpg)
![5 Symptoms date](https://user-images.githubusercontent.com/5230720/93128784-02c5bb00-f69e-11ea-8e80-22ba9fbe4a47.jpg)
![6 Test dates](https://user-images.githubusercontent.com/5230720/93128786-02c5bb00-f69e-11ea-90c2-8d8da8c1418e.jpg)
![7 Confirmation](https://user-images.githubusercontent.com/5230720/93128788-035e5180-f69e-11ea-921a-3b7f5ee9213c.jpg)

With the flow:
![narrow timeline flow](https://user-images.githubusercontent.com/5230720/93128883-2426a700-f69e-11ea-9ac2-1cbed66dea67.jpg)

**Comment by emilykuret** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create error messaging for traceback duration](https://trello.com/c/Ly3YjDGq/519-create-error-messaging-for-traceback-duration)

**Comment by timarney** [comment]
@smcmurtry has started testing on this.

**Comment by timarney** [comment]
Closing notes will be added to the PR https://github.com/cds-snc/covid-alert-app/pull/1109
