### ISSUE TITLE
Bug | Explain why older phones don't work

### ISSUE THREAD

**Issue by mgifford** [cds-snc/covid-alert-app#1099]
# Summary 

There needs to be some summary about why this doesn't work for older phones.

Is it the OS & the challenge of developing for older operating systems?  Is it just that legacy smartphones don't have sufficiently precise geo-location?  Maybe it boils down to the Bluetooth protocols.  

Whatever it is, it would be good to state it clearly.  For those of us in the web business it's obvious that building for older phones is going to be a real challenge (if it is at all possible).  

Anyways, useful to just point the finger at hardware, OS, budgets or just time...

**Comment by theetrain** [comment]
I'm curious to know as well. Though I don't know the true answer, here's some interesting information:

Bluetooth Low Energy is required to run COVID Alert and exchange tokens with other devices while being battery-efficient. Bluetooth Low Energy support was first introduced in [Android 4.3 API Level 18](https://developer.android.com/guide/topics/connectivity/bluetooth-le). 

Some of the first devices to use Android 4.3 were the Galaxy Nexus and Nexus 4 in July 2013 ([reference](https://en.wikipedia.org/wiki/Android_Jelly_Bean#Release)). 

Bluetooth Low Energy was first specified as part of Bluetooth 4.0 introduced in 2009, and available in phones such as the Galaxy S3 and Nexus 4 in 2012.

COVID Alert targets SDK version 23 at minimum, which is Android 6 that released in October 2015. On paper, it sounds like contract tracing may work on older versions of Android, though I am not an Android developer and don't fully grasp its nuance of device support. Nonetheless, an explanation is appreciated.

**Comment by ajayyy** [comment]
On iOS, the device must get a software update (which is limited to newer phones).

**Comment by timarney** [comment]
Thanks @mgifford this has been flagged back to the team - for possible support content outside of this repo.

Closing the issue here as we're trying to keep this mostly for bugs etc.. with the app.
