### ISSUE TITLE
Todo: Compare with other open source apps

### ISSUE THREAD

**Issue by mgifford** [cds-snc/covid-alert-app#1101]
# Summary

Just noticed this app from the NL https://github.com/minvws/nl-covid19-notification-app-website

Worth looking to see what can be learned from it. I like the transparency in design principles & Features, requirements and standards

**Comment by timarney** [comment]
Thanks @mgifford this has been flagged back to the team.  

Closing the issue here as we're trying to keep this mostly for bugs etc.. with the app.
