### ISSUE TITLE
Bug | Exposure notification received but "no exposure detected" in app

### ISSUE THREAD

**Issue by rosslh** [cds-snc/covid-alert-app#1113]
# Summary

Someone I know received a notification from the COVID Alert app that she had "4 potential exposures this week". Within the app however, it says "no exposure detected".

# Steps to reproduce

Receive a notification that you've been exposed. Check the app and see that you have apparently not been exposed.

# Environment

- iPhone 11
- Software version 13.6.1

# Unresolved questions / Out of scope

Is this notification just a bug which is safe to ignore?

**Comment by rosslh** [comment]
I think this is a duplicate of #1074 actually. Maybe the language of that notification should be toned down because "potential exposure" can be interpreted to mean "you were in contact with someone who has COVID and were potentially exposed".

**Comment by timarney** [comment]
Yes this is a duplicate.  That wording is from the OS level and yes it was very confusing for users.  It's been updated in iOS 14 and I believe 13.7 as well.
