### ISSUE TITLE
Implement Safety Net on Android

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-alert-app#1116]
**Why?**
To ensure calls to the server are coming from the app

**What is Safety Net?**
https://developer.android.com/training/safetynet/attestation

> The SafetyNet Attestation API is an anti-abuse API that allows app developers to assess the Android device their app is running on. The API should be used as a part of your abuse detection system to help determine whether your servers are interacting with your genuine app running on a genuine Android device.

**Comment by timarney** [comment]
As a starter we can look into using:
https://github.com/rajivshah3/react-native-google-safetynet

**Comment by ajayyy** [comment]
If doing this, only check `basicIntegrity`, as otherwise you will be breaking the app for many legitimate users with unlocked bootloaders or custom roms.

**Comment by timarney** [comment]
Closing this for now.
