### ISSUE TITLE
Matching keys in logs but app reports no exposures

### ISSUE THREAD

**Issue by dmkc** [cds-snc/covid-alert-app#1163]
# Summary | Résumé

The app shows no exposures but the iOS COVID logs show instances of matching keys. Screenshots attached.

# Environment | Environnement logiciel
iOS 13, Ontario resident

![IMG_3450](https://user-images.githubusercontent.com/118149/94826586-76bdce00-03d5-11eb-9503-92b09d9b0341.PNG)
![IMG_3339](https://user-images.githubusercontent.com/118149/94826590-76bdce00-03d5-11eb-9242-a10c4906a57d.PNG)
![IMG_3340](https://user-images.githubusercontent.com/118149/94826591-77566480-03d5-11eb-96fd-0726982e2521.PNG)
![IMG_3338](https://user-images.githubusercontent.com/118149/94826593-77566480-03d5-11eb-9116-e2096619fece.PNG)

**Comment by timarney** [comment]
Matched Key Count (Apple) | Number of matches (Android): This is the number of random codes related to a positive test result that may have been within bluetooth range of your phone. Having a number above 0 for the matched key count does not necessarily mean you’ve been exposed. These codes could come from phones that were more than 2 metres away, or were near you for a very short time.  The app is more granular when looking at exposures particularly for duration and proximity.

Open COVID Alert to find out your exposure status according to the settings from Health Canada (more than 15 minutes, less than 2 metres apart, over the past 14 days).

**Comment by dmkc** [comment]
ahhhh, thanks so much for the explanation!

**Comment by lepinsk** [comment]
@timarney I'm unable to find Apple docs on the expectation around how `MatchCount` should behave. I've seen [it reported elsewhere](https://www.reddit.com/r/CanadaCoronavirus/comments/ixdouk/reset_covid_alert_app_after_exposure/g6j6a9d/) that the `KeyCount` value should reset at midnight, which appears to be tracking what I see in my data, however I can't understand why one check would show a `MatchCount` of 1, and then a subsequent check a few minutes later (with an increased `KeyCount`) has gone back to 0:

```js
    {
      "Timestamp" : "2020-10-08 19:18:46 -0400",
      "Files" : [
        {
          "Hash" : "B2F0EB6A1B9775EA5836D50DE9E89CC8931085DDE1CAD1300645A3B7B39FE8F6",
          "MatchCount" : 0,
          "KeyCount" : 1051,
          "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid",
          "Timestamp" : "2020-10-08 19:18:46 -0400"
        }
      ],
      "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid"
    },
    {
      "Timestamp" : "2020-10-08 19:06:00 -0400",
      "Files" : [
        {
          "Hash" : "5585E0E94E89766862AEE3649086AF4E9BE13B6585A4E8102A823C0F407A5BC4",
          "MatchCount" : 1,
          "KeyCount" : 1019,
          "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid",
          "Timestamp" : "2020-10-08 19:06:00 -0400"
        }
      ],
      "AppBundleIdentifier" : "ca.gc.hcsc.canada.stopcovid"
    },
```

How can there be a match with 1019 keys, but with 32 new keys added there's now *no* match?
