### ISSUE TITLE
Be able to adjust amount of minutes threshold to lower values than 15 minutes

### ISSUE THREAD

**Issue by fredvb** [cds-snc/covid-alert-app#1172]
As a Canadian citizen, could I build a personal build that will work with the official built ones, if I manually install my version ?

If so, is there a way for me to adjust the 15 minutes exposure threshold to 5 minutes ?

**Comment by timarney** [comment]
Thanks for the question @fredvb you won't be able to do a local build as the app requires [entitlements](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_exposure-notification) which are only given to Public Health authorities.

As far as adjusting the threshold that's not currently possible.

**Comment by LeCanardQuoi** [comment]
A 5 minutes timer configuration may become more important with a more virulent strain of the virus and more stringent lockdown measures in red zones.
