### ISSUE TITLE
Lower API level version requirement 

### ISSUE THREAD

**Issue by fredvb** [cds-snc/covid-alert-app#1173]
![Screenshot_20201004-003652](https://user-images.githubusercontent.com/8552881/95007116-f4522b80-05d9-11eb-967a-4d72db07c2c9.png)

Just forwarding a request I saw in the Google Play reviews that I thought should be looked into.

**Comment by timarney** [comment]
Thanks @fredvb I'll bring this back to the team.

Pulled this from the Google docs for reference.  

https://developers.google.com/android/exposure-notifications/exposure-notifications-api#architecture

> For your app to work on all devices, set your minSdkVersion to version 6.0 (API level 23) or higher. The framework works on some devices as low as version 5.0 (API level 21), so using this version is an option to increase the number of devices eligible. If you decide to set the minSdkVersion to API level 21, you should test your app on the most popular Android 5.0 devices in your country to ensure that your app works as intended.

**Comment by timarney** [comment]
This has been brought up for internal discussions.  Will open up a new issue pending the outcome of those.
