### ISSUE TITLE
App on/off status and iPhone status out of sync and cannot discover a way to recover

### ISSUE THREAD

**Issue by steve-h** [cds-snc/covid-alert-app#1174]
# Summary | Résumé

> I am running IOS 14.2 beta 2 on iPhone X. After a phone restart, the next time the Covid App was opened, it claimed the collection was off.

<img width="300" src="https://user-images.githubusercontent.com/1298089/95127688-63d53180-0726-11eb-8c42-12290dee3c89.PNG">

and the iPhone screen shows:

<img width="300" src="https://user-images.githubusercontent.com/1298089/95127745-80716980-0726-11eb-9c89-26f99b423684.PNG">

The App does not seem to re-synchronize to the ON state and the iPhone screen promises to delete all my exposure data if I try the turn off and on fix. So I assume the onus falls to the Covid App to get itself On again somehow.
---

# Steps to reproduce | Étapes à reproduire

> Sequence from memory of how I got out of sync; cannot repeat as my phone is in an out-of-sync state now.

1. Covid app was working on IOS14.2

2. Upgraded to IOS 14.2 beta 2 developer beta

3. Covid App worked (I'm pretty sure but not 100% on this)

4. iPhone restarted.

5. Covid App opened now in off state.

# Environment | Environnement logiciel

> iPhone X IOS14.2 beta 2 (developer beta)

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

> This out of sync is not a desired state. If it remains possible the a help procedure to correctly recover sync without losing the last 14 days of exposure data would be desirable

**Comment by timarney** [comment]
@steve-h we're currently following up with Apple for some related issues around the region setting.

If you navigate to Settings -> Covid Alert -> Exposure Notifications -> "Health Canada" ... is that screen showing as blank?

I'm currently running iOS 14.2 beta and see:

<img width="300" src="https://user-images.githubusercontent.com/62242/95201494-07b5f000-07ae-11eb-8faf-07268967cc52.png"> 

Settings -> Exposure Notifications  

<img width="300" src="https://user-images.githubusercontent.com/62242/95200562-91fd5480-07ac-11eb-9cf8-2b27f45fb0f8.png">

**Comment by steve-h** [comment]
Now things are weird/better. First of all the Covid app shows green and on status today and I didn't do anything. Yesterday the screen that you are asking about was totally black/blank.

So with that I am attaching shots of the region stuff that had been showing blank. The last screen has a black empty bit that I had seen when the exposure feature was enabled for IOS14 betas.

![IMG_6890](https://user-images.githubusercontent.com/1298089/95205073-e277b080-07b2-11eb-9894-2133f643ff9b.PNG)
![IMG_6891](https://user-images.githubusercontent.com/1298089/95205097-ec011880-07b2-11eb-97d5-4f6abc95eb0f.PNG)
![IMG_6892](https://user-images.githubusercontent.com/1298089/95205117-f1f6f980-07b2-11eb-9739-2645414108cf.PNG)

**Comment by steve-h** [comment]
Something did happen overnight. The iPhone auto-upgraded the App to version 1.0.10. So the good news is that things at least went back to what I had seen before. The odds of reproducing how I got the App out of sync are maybe less.

I will leave it as is for now and check what happens if I restart the phone in the future.

**Comment by steve-h** [comment]
An extra screenshot from Apple Exposure > Share a COVID-19 
![image](https://user-images.githubusercontent.com/1298089/95207528-f670e180-07b5-11eb-8a61-a6774b45bddd.png)

**Comment by timarney** [comment]
Very interesting thanks for the screenshots.  The latest update on our side was just a content update but looks like an app update regardless of what it was kicked off some other events on the OS layer.

**Comment by steve-h** [comment]
Yes. Whatever code ran on app install may need to run from the Covid App side in case an out of sync occurs like it did for me. Recovery from the Apple side looks like it will delete exposure data and it is likely the onus will always be for the app to at least adopt the Apple state.

**Comment by steve-h** [comment]
Yes, I do have remove region. It is in the earlier screenshots. I will not use it unless you want me to.

**Comment by emilykuret** [comment]
Hey! When we flagged this for Apple, they mentioned a potential work around for this could be to remove the region and reselect Canada. If we hear anything else, we will let you know!

**Comment by timarney** [comment]
Latest from Apple testing is try deleting the app "Remove App" from the device and re-install (onboard etc...)

After that.

> Settings > Exposure Notification > Health Canada > Set As Active Region. Upon returning to the app, it now showed as alerts active.


Note: Removing the app doesn't remove the exposure checks

**Comment by steve-h** [comment]
Well I deleted Covid alert and reinstalled. The data still is in the Apple cache.
I do not see a >Health Canada>  part to the region stuff. Looks like all the screenshots in thread.
It takes a little nerve on delete as you get the standard "all your data will be deleted" warning, and this notification

![image](https://user-images.githubusercontent.com/1298089/95258312-900ab400-07f3-11eb-9db8-79de8d352159.png)

**Comment by timarney** [comment]
Hi @steve-h 

We're told  iOS 14.2 beta 4 might fix this issue.  

We're looking for some end users that we're experiencing this issue that are also running the beta.

Would you be able to confirm?

**Comment by steve-h** [comment]
Indeed the region does work in beta 4. It shows health Canada now instead of black rect. You can close issue if you are not worried about the original out of sync. It could be a beta thing as I started using COVID alert on ios14 beta.

**Comment by timarney** [comment]
Great - thanks for reporting and testing.  We should see patch in an upcoming iOS release.
