### ISSUE TITLE
Only client code, no server?

### ISSUE THREAD

**Issue by codebam** [cds-snc/covid-alert-app#1175]
This is only the source of the client, not the server. It in no way proves that you are not using the data collected from the app in malicious or unintended ways.

In order to solve this I would like to propose that the server source code be made open as well. This would allow the core of the service to be audited by security professionals and would improve user trust.

**Comment by codebam** [comment]
My bad didn't see https://github.com/cds-snc/covid-alert-server

**Comment by CalvinRodo** [comment]
You can also see our infrastructure code here: https://github.com/cds-snc/covid-alert-server-staging-terraform
