### ISSUE TITLE
[BVC-158] Keys should be wiped after leaving diagnosed state.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#1178]
# Summary | Résumé

Keys created during the initial OTK exchange step are not removed from local storage after leaving the diagnosed state. As a matter of keeping things clean, would recommend wiping any artifacts related to previous diagnosis state.

# Environment | Environnement logiciel

Both Android / IOS.

**Comment by obrien-j** [comment]
Recommend a low priority tag on this, but it should be a relatively quick fix.

**Comment by maxneuvians** [comment]
Solution path:

1. Add to `removeItem `to the interface: https://github.com/cds-snc/covid-alert-app/blob/master/src/services/ExposureNotificationService/ExposureNotificationService.ts#L73-L76

2. Add a `removeItem(SUBMISSION_AUTH_KEYS)` call to: https://github.com/cds-snc/covid-alert-app/blob/master/src/services/ExposureNotificationService/ExposureNotificationService.ts#L300

3. Add a `captureMessage` to make sure you have logging set up.

**Comment by craigzour** [comment]
I made a PR providing an implementation of @maxneuvians 's solution. https://github.com/cds-snc/covid-alert-app/pull/1344

**Comment by timarney** [comment]
Given were mostly maintenance work at this point we won't be implementing any changes for this scenario
