### ISSUE TITLE
[BVC-155] Review  LC_LOAD_WEAK_DYLIB load command for the library BackgroundTasks

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#1179]
# Summary | Résumé

LC_LOAD_WEAK_DYLIB load command is present for the library BackgroundTasks - this is best avoided since there's also a LC_RPATH that adds @executable_path/Frameworks to the search path and that directory doesn't exist. 

These two load commands could be used to inject a third party library into the app.

<more detail>

The binary has a weak dependence on a library called BackgroundTasks. It also has a built-in library search path @executable_path/Frameworks. As far as I can see, that library doesn’t exist on my device and the path either. This can be used to inject a third party library into the app. For the actual mechanics on how to perform the DLL injection, please consult this awesome presentation:

https://speakerdeck.com/patrickwardle/dll-hijacking-on-os-x-number-at-percent-and-yeah

# Steps to reproduce | Étapes à reproduire

# Environment | Environnement logiciel

IOS

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

**Comment by obrien-j** [comment]
Low priority recommended, but would appreciate a set of mobile dev eyes on for initial triage.

**Comment by timarney** [comment]
@jeberhardt can you comment on this - as you've been digging into the background tasks the most at this point.

**Comment by craigzour** [comment]
@obrien-j Can you tell me where to look exactly for the "LC_LOAD_WEAK_DYLIB" load command? I can't find it.

**Comment by timarney** [comment]
Given were mostly maintenance work at this point we won't be implementing any changes for this scenario
