### ISSUE TITLE
[BVC-104] Review inclusion of libhermes-executor-debug.so in release APK

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#1180]
# Summary | Résumé

Hermes is a JavaScript engine optimized for React Native

debug versions of a library should be included in debug builds only. This is backed by MSTG-CODE-2 as per https://mobile-security.gitbook.io/masvs/security-requirements/0x12-v7-code_quality_and_build_setting_requirements

However, we are ending up with libhermes-executor-debug.so and libhermes-executor-release.so in our release APK. It might be for the better (see below) but still is not great.

D:\WFH\project\covidmobile20200607\node_modules\react-native\react.gradle

A Facebook module tries the following:

<covidshield>\node_modules\react-native\ReactAndroid\src\main\java\com\facebook\hermes\reactexecutor\HermesExecutor.java

static {
  // libhermes must be loaded explicitly to invoke its JNI_OnLoad.
  SoLoader.loadLibrary("hermes");
  try {
    SoLoader.loadLibrary("hermes-executor-debug");
    mode_ = "Debug";
  } catch (UnsatisfiedLinkError e) {
    SoLoader.loadLibrary("hermes-executor-release");
    mode_ = "Release";
  }
}
What happens at runtime is a failed attempt to load libhermes-executor-debug.so 

07-07 08:23:46.311  9334  9355 D SoLoader: libhermes-executor-debug.so found on /data/data/com.google.android.apps.exposurenotification/lib-main

07-07 08:23:46.334  9334  9355 E SoLoader: couldn't find DSO to load: libhermes-executor-debug.so caused by: couldn't find DSO to load: libhermes-inspector.so caused by: dlopen failed: cannot locate symbol "_ZTIN8facebook6hermes8debugger13EventObserverE" referenced by "/data/data/com.google.android.apps.exposurenotification/lib-main/libhermes-inspector.so"...
07-07 08:23:46.334  9334  9355 E SoLoader: couldn't find DSO to load: libhermes-executor-debug.so caused by: couldn't find DSO to load: libhermes-inspector.so caused by: dlopen failed: cannot locate symbol "_ZTIN8facebook6hermes8debugger13EventObserverE" referenced by "/data/data/com.google.android.apps.exposurenotification/lib-main/libhermes-inspector.so"...
07-07 08:23:46.334  9334  9355 E SoLoader: couldn't find DSO to load: libhermes-executor-debug.so caused by: couldn't find DSO to load: libhermes-inspector.so caused by: dlopen failed: cannot locate symbol "_ZTIN8facebook6hermes8debugger13EventObserverE" referenced by "/data/data/com.google.android.apps.exposurenotification/lib-main/libhermes-inspector.so"...
07-07 08:23:46.334  9334  9355 E SoLoader: couldn't find DSO to load: libhermes-executor-debug.so caused by: couldn't find DSO to load: libhermes-inspector.so caused by: dlopen failed: cannot locate symbol "_ZTIN8facebook6hermes8debugger13EventObserverE" referenced by "/data/data/com.google.android.apps.exposurenotification/lib-main/libhermes-inspector.so"...
Followed by a successful load of the release version

07-07 08:23:46.334  9334  9355 D SoLoader: libhermes-executor-release.so found on /data/data/com.google.android.apps.exposurenotification/lib-main
Conceivably, if someone replaced libhermes-executor-debug.so with one that loads properly, they could get code execution.

I don't know if it's a good solution, but please consider checking if the following code <covid-shield-mobile>/blob/master/android/app/build.gradle can be changed.

if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
can be changed to 

if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-release.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

<more detail>

More changes might be needed, at least in the following React-provided files, which are not within our control (unless we want to routinely import the React code base and make modifications to it):

node_modules/react-native/ReactAndroid/build.gradle

node_modules/react-native/ReactAndroid/src/main/java/com/facebook/hermes/reactexecutor/Android.mk

 

    - def hermesAAR = file("$hermesPackagePath/android/hermes-debug.aar")
    + def hermesAAR = file("$hermesPackagePath/android/hermes-release.aar")
    if (!hermesAAR.exists()) {
        throw new GradleScriptException("The hermes-engine npm package is missing \"android/hermes-debug.aar\"")
    }

# Environment | Environnement logiciel

ios

**Comment by timarney** [comment]
Looks like there's an issue here:
https://github.com/facebook/react-native/issues/29064

**Comment by timarney** [comment]
https://github.com/facebook/hermes/issues/96#issuecomment-552327863

**Comment by maxammann** [comment]
Just fixed this upstream: https://github.com/facebook/react-native/pull/30303

**Comment by craigzour** [comment]
Looks like the PR from @maxammann has not been merged. Waiting on Gradle pluging v4.2 to be released.

**Comment by maxammann** [comment]
@craigzour yep, I follow the Gradle plugin releases right now. Will fix this asap :)

**Comment by timarney** [comment]
Will re-open as needed.

**Comment by maxammann** [comment]
@timarney  did you check whether this problem still exists? I'm asking because I'm thinking about fixing it again upstream.

If you did not check, then this is no problem.

**Comment by timarney** [comment]
Looks like the problem still exists

<img width="380" alt="Screen Shot 2021-06-24 at 11 38 39 AM" src="https://user-images.githubusercontent.com/62242/123292530-20536b00-d4e1-11eb-9268-db1b26331737.png">

**Comment by maxammann** [comment]
Thank you for checking!

You can close this though I think. This needs upstream fixing and it is not critical.
