### ISSUE TITLE
[BVC-117] Possible Denial of Service - Application accepts very large payload for diagnosis keys file

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#1182]
# Summary | Résumé

The download diagnosis file operation is executed periodically to retrieve the diagnosis keys from the server. It is possible for a malicious server to perform a denial of service attack by returning a large keys file which could potentially consume all of the memory available to the app and would eventually crash the application. Based on code review of the downloadDiagnosisKeysFile in CovidShieldModule.kt, we can confirm that the application isn’t restricting the size of received payload and just blindly saves the diagnosis key files without any validation. We were able to send a diagnosis key file of size 100MB and confirm via the debugger that the data was getting saved to the keys.zip file.

Possible solutions:

Limit the size of the receive payload, it is not clear whether this capability is supported by OKHttpClient.

 Not a great solution, but if (1) is not possible, the application should reject the response if the data > 16M or an appropriate maximum payload size as per https://developers.google.com/android/exposure-notifications/exposure-key-file-format#file-format and agreement with the server development team.

**Comment by obrien-j** [comment]
Recommended as low priority given attack path, but likely worth bundling with #1181

**Comment by maxneuvians** [comment]
The easiest way to do this would be to do a HEAD query and extract the content size before doing the actual GET. For simplicity it might make sense to do this in the TypeScript layer vs. in the bridge code. In that case you may want to insert a check here: https://github.com/cds-snc/covid-alert-app/blob/master/src/services/BackendService/BackendService.ts#L53

**Comment by craigzour** [comment]
Same as #1181 . cc @timarney

**Comment by timarney** [comment]
Given we're mostly doing maintenance work at this point we won't be implementing any changes for this scenario.
