### ISSUE TITLE
[BVC-120] Mobile app - Insufficient validation of KeyClaim response

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#1183]
# Summary | Résumé

The application can be tricked into believing it has received a valid Key Claim Response by simply using invalid tags in the response message. Presumably, this will result in a failure later on, when the app tries to use the server’s Public Key. The relevant code is located in the KeyClaimResponse decode function in covidshield.js.

This issue was easily demonstrated with an HTTP server that sends response data that contains 100 bytes of zeros data back to the client in response to the POST /claim-key request. The POST request is sent when the user enters the 8-digit number to initiate the uploading of TEKs, after being diagnosed.  Because the app thinks the response is valid, it displays the "Agree" screen to request user's permission to download the TEKs.  When the user selects Agree, an error message is returned, "Random codes could not be uploaded You did not give permission".  The application is not able to recover and is stuck in the "upload your random codes" state.

The decode function should be updated as follows:

reject the response if an invalid tag is provided with an appropriate message to the user

validate the fields extracted from the message

**Comment by obrien-j** [comment]
Recommend low priority given attack path, but bundled with #1181 and #1182

**Comment by maxneuvians** [comment]
`covidshield.js` is an autogenerated file from the protobuf definition, so making changes in there is not an ideal solution. One could ideally throw in some simple validation around here: https://github.com/cds-snc/covid-alert-app/blob/master/src/services/BackendService/BackendService.ts#L121

ex: `if(serverPublicKey === clientPublicKey) {throw err}` or something to that effect

**Comment by craigzour** [comment]
@maxneuvians According to the solution you are proposing. Both the serverPublicKey and the clientPublicKey should be equal?

**Comment by craigzour** [comment]
I have been doing some investigation on this and I am not sure if there is a robust solution to it. For sure we could make sure that Error code is valid by looking at the raw value (between 0 and 5) but for the other fields (especially the server public key) I am not sure if we can validate anything. Having a bunch of 0 or a faked key would be the same for the application (meaning user will still be stuck). For now I would recommend that we make sure the backend returns a proper response (I have seen existing unit-tests for that) and also to find a way to make sure we always communicate with the right backend (having DeviceCheck and SafetyNet implemented will help on that front). cc @timarney

**Comment by timarney** [comment]
Given we're mostly doing maintenance work at this point we won't be implementing any changes for this scenario.
