### ISSUE TITLE
Request new feature | Demander une nouvelle fonctionnalité

### ISSUE THREAD

**Issue by calcem** [cds-snc/covid-alert-app#1186]
# Summary | Résumé

>The weekly reminder notification is, in my opinion, unnecessary. It is a unfriendly interaction with the application, given that the application name is Exposure Notifications. I feel that there are only two reasons the app should send me a notification, 1. I have been in close contact to someone who has tested positive, 2. Notifying me that my Bluetooth is off 

# Design detail | Précisions au sujet de la conception

> Remove the weekly reminder notification, or change the name that shows up when a notification is sent. 
![20201006_222241](https://user-images.githubusercontent.com/9713765/95280304-b3008c80-0822-11eb-98bf-5653839d478e.jpg)

**Comment by CalvinRodo** [comment]
Thanks for the issue, unfortunately though this is beyond our control, this is an OS level notification that is displayed by Android and (a slightly similar one on) iOS when Exposure Notifications is on. 

Google mentions it here (Emphasis mine): 
https://support.google.com/android/answer/9991216

>The updates also include Settings updates that further enhance clarity, transparency, and control. The Exposure Notifications Settings now includes a simple on/off toggle at the top of the page. **_Users will also see a weekly reminder that exposure notifications are turned on._**
