### ISSUE TITLE
App/docs does not explain what "potential" exposure means

### ISSUE THREAD

**Issue by sromkey** [cds-snc/covid-alert-app#1200]
As a user, when I receive a notification of potential exposure I want to be able to find out what that means and if any action is required. 

I received a potential exposure notification on my lock screen today but I can't seem to find any information on what that means. I _think_ it means I was near a diagnosed person but not within the 2 m, 15 minute range but I'm just guessing. When I open the app it just gives the usual "No exposure detected" screen.

Thanks for your consideration! And apologies if this information does exist somewhere and I've just failed to find it.

**Comment by timarney** [comment]
Hi @sromkey 

Please see #1074 for some background information and also this thread 

https://twitter.com/CDS_GC/status/1313933098522996738

Please let me know if that covers what your looking for :)

**Comment by sromkey** [comment]
That is 100% what happened, which someone on Twitter also just explained to me! Closing with apologies, I had no idea this was a thing IOS was doing! This is what happens when you check your notifications at 5:30 am and proceed to file a Github issue :facepalm:

**Comment by timarney** [comment]
No apology needed at all.  It's a very confusing notification.
