### ISSUE TITLE
Request new feature | incorporate contextual data like microcovid.org

### ISSUE THREAD

**Issue by kbroughton** [cds-snc/covid-alert-app#1237]
# Summary | Résumé

Microcovid.org and the microcovid.org/spreadsheet could help app users develop intuition for modifying behavior based on risk.
An app extension/companion could allow users to provide richer context to supplement the bluetooth tracking and get more precise recommendations based on a better estimate of risk.

Since C19 app is only taking a subsample of actual contacts (those who have phones on and app installed), it makes sense to fill in some of the apps' blind-spot by taking estimates of activity and covid+ density into account.

This could be done without any change to the client's privacy model except that the app holds slightly more info, but doesn't need to share any of that with the server.  A person diagnosed with covid could optionally add context such as if they 'almost always' wear a mask outdoors.

# Design detail | Précisions au sujet de la conception

This probably doesn't belong completely within the C19 app, but microcovid.org is a really neat idea for getting more granular on risk analysis - https://www.microcovid.org/spreadsheet. 

I couldn't quite tell if https://github.com/cds-snc/covid-alert-app/pull/1235 was heading in this direction.

You could imaging having a companion app, or opt-in local data to enrich the proximity data. The simplest would be if the covid+ patient could specify if they wore a mask when not social distancing in public or not. That would impact the risk of transmission by 90%. Similarly, if the person checking their risk could input whether they wore a mask when outside, it could give risk estimates with greater accuracy.

For even greater precision, one could imagine having the hard-and-fast blue-tooth based contact tracing supplemented with general risk-per-zone + activity data. For example, if there was a spike around the downtown core last tuesday, and C19 shows no contacts, it might miss contacts in the blind-spot.

The key concept introduced here is the Risk Budget.
The main purpose is to add additional education features to the app while making risk estimates more accurate. Context or Microcovid data enrichment can help reduce the frustration of app users not knowing how to interpret an alert. It can also empower users by helping build confidence in estimating risk of various activities. 

This concept is already present in some Covid19 Stats dashboards where they might have
Confirmed Covid Tests per 100,000                        Adjusted/Expected Rate per 100,000 (since not everyone gets tested)

The equivalent dashboard here might show
Measured Risk based on phone2phone contact          Estimated Risk based on density of covid + your activities

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

**Comment by timarney** [comment]
cc: @sidewalkballet ☝️

**Comment by timarney** [comment]
Thanks @kbroughton

This has been brought back to the team for further discussion. Going to close this issue and will re-open as needed.
