### ISSUE TITLE
Add info on how to check what apps are using Location services

### ISSUE THREAD

**Issue by kbroughton** [cds-snc/covid-alert-app#1253]
# Summary | Résumé

It's a little disconcerting and confusing to be told that the app doesn't track your location but does require enabling Location services for all apps for the google/ios bluetooth system to work. The docs do a good enough job of describing why, but perhaps you could add links to iOs and Android pages that explain how to check which apps are actually using the Location service and remove them as necessary. https://support.google.com/android/answer/6179507 for example.

# Design detail | Précisions au sujet de la conception

Explain to users how to check what apps are using location settings and if possible provide an easy link to check from within the app.

There are several closed issues relating to this:
https://github.com/cds-snc/covid-alert-app/issues/1130
https://github.com/cds-snc/covid-alert-app/issues/891
https://github.com/cds-snc/covid-alert-app/issues/521

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

None

**Comment by timarney** [comment]
Thanks @kbroughton 

This has been brought back to the team for further discussion. Going to close this issue and will re-open as needed.
