### ISSUE TITLE
App not performing any exposure checks

### ISSUE THREAD

**Issue by hobindar** [cds-snc/covid-alert-app#1257]
# Summary | Résumé

After downloading the app and enabling it, a couple exposure checks are performed, sometimes with exactly 0 diagnosis keys. From this point on, the app never performs another exposure check (according to Google's UI).

See picture at bottom of issue for clarification. The picture is from November 22nd at 5:35 pm. Note that, on an earlier reproduction, I had waited a whole week rather than two days, and the issue was still observable.

It's worth noting, this is new behavior (that is, it used to work just fine) and doesn't seem to happen on all (or even most) phones. Notably, it occurs on my OnePlus 3T, but does not occur on either the Pixel 2 nor 3.

Wiping COVID Alert's storage does not resolve the issue. Nor does reinstalling the app.

---

# Steps to reproduce | Étapes à reproduire

1. Install COVID Alert 
2. Open COVID Alert
3. Navigate through the setup
4. Enable Exposure Notifications when prompted to
5. Select "Ontario"
6. Close the app via the home button
7. Open the Settings app
8. Navigate to "Google" > "COVID-19 exposure notifications" > "Exposure checks"
9. Observe there are a couple exposure checks. They may or may not indicate 0 diagnosis keys
10. Wait several days
11. Repeat steps 7 and 8
12. Observe that there have been no new exposure checks

---

# Environment | Environnement logiciel

- OnePlus 3T
- Stock OnePlus firmware
- Android 9, build number `ONEPLUS A3000_28_191104`
- Google Play Services version `20.42.17 (100400-342117392)`
- Logs can be captured on request

---

![Screenshot_20201122-173510](https://user-images.githubusercontent.com/4131146/99919122-7103ab00-2ce9-11eb-995a-5df0ebf3b078.jpg)

**Comment by timarney** [comment]
Hi @hobindar 

A new release rolled out yesterday based on some users seeing gaps in the logs.  If you can update and report back if that fixes the issue that would be great.

**Comment by hobindar** [comment]
@timarney, looks like the latest release (1.1.1) does indeed fix the problem.

I'm going to go ahead and close this issue. Thanks!
