### ISSUE TITLE
Request new feature | Application carnet de vaccination covid 19

### ISSUE THREAD

**Issue by ilyhel** [cds-snc/covid-alert-app#1258]
# Résumé

Bientôt arriver de vaccin de covid-19 mais y a il  un processus de gestion?

Pourquoi pas une application de gestion de vaccin, prise de rendez-vous, ordre de priorité, gestion de distribution de vaccin, disponibilité en stock, rapports de situation liéé au processus de vaccination

**Comment by timarney** [comment]
cc: @sidewalkballet ☝️

**Comment by timarney** [comment]
Thanks @ilyhel 

This has been brought back to the team for further discussion. Going to close this issue and will re-open as needed.
