### ISSUE TITLE
Request new feature | Show user how many contacts were logged today

### ISSUE THREAD

**Issue by LeadSongDog** [cds-snc/covid-alert-app#1264]
# Summary | Résumé

Day after day, all that I see is the green thumb up. Yay!  But I get no sense from the app just how often I'm taking the chance of exposure, nor how many of the people I come into contact with are running the app: are the people around me all nonexposed, or are they just running dark, with BT off?  

# Design detail | Précisions au sujet de la conception

Each day, the app could show the user the previous day's tally of how many contact encounters were logged. If that tally is zero, report something like "_Either you were home alone yesterday or nobody you met was running the app. Please tell your friends how easy it is to use_."

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

> Are there any related issues or tangent features you consider out of scope for this issue that could be addressed in the future?

---

> Y a-t-il des questions connexes que vous considérez hors sujet et qui pourraient être abordées plus tard?

**Comment by timarney** [comment]
cc: @sidewalkballet ☝️

**Comment by LeCanardQuoi** [comment]
For a newbee, how does one find out how a proposed enhancement is making it through? Is there an other level of access required (e.g. project)? Also wish to know if the existing ENS framework (design stuff) currently provide for this???

**Comment by timarney** [comment]
Thanks @LeCanardQuoi

This has been brought back to the team for further discussion.  Going to close this issue and will re-open as needed.


> For a newbee, how does one find out how a proposed enhancement is making it through? 

1) There is discussion about opening up a public backlog of items 
2) Outside of that issues will be tagged and or referenced i.e. 

https://github.com/cds-snc/covid-alert-app/issues/1300
