### ISSUE TITLE
Seeking help to understand usage of Risk Threshold

### ISSUE THREAD

**Issue by amarbayar** [cds-snc/covid-alert-app#1271]
Hello CDS SNC Team, 

First of all, thank you all for the great work on documenting and open-sourcing the projects. Writing from Mongolia. We had been able to prevent local transmission of COVID until early November. Unfortunately, early November we have had our first case(s) of local transmissions and the number has hit 300+ already; hence, we have been in lockdown for over 2 weeks now. 

The Mongolian tech community has gotten together and started working on building a privacy-preserved contact tracing app based off of your open source projects. 

We are currently waiting for the entitlement (Exposure Notification) approval. Development work is mostly complete, but we are unable to test due to not having the entitlement yet. 

One of our biggest concerns is about the `Risk Threshold`. As you may have already been aware of, UK has had a case where the NHS COVID app download reached 19 million but due to having the Risk Threshold set at `15 min` their use-case showed that fewer people were getting notifications than necessary. Reference: https://www.dailymail.co.uk/sciencetech/article-8904855/NHS-Covid-19-contact-tracing-app-using-wrong-risk-threshold.html

I am reaching out to see if you have done any research on the `Risk Threshold` and what your decision was as far as the various parameters in the .json configuration: 

```
{
minimumRiskScore: 0,
minimumExposureDurationMinutes: 2,
attenuationDurationThresholds: [1, 2],
attenuationLevelValues: [1, 2, 3, 4, 5, 6, 7, 8],
attenuationWeight: 50,
daysSinceLastExposureLevelValues: [1, 2, 3, 4, 5, 6, 7, 8],
daysSinceLastExposureWeight: 50,
durationLevelValues: [1, 2, 3, 4, 5, 6, 7, 8],
durationWeight: 50,
transmissionRiskLevelValues: [1, 2, 3, 4, 5, 6, 7, 8],
transmissionRiskWeight: 50,
}
```

It might be that the numbers should come from each country's Health Authorities. If that is the case, do you have any documentation what each of these config parameters indicate and how they co-relate with each other? We know what `minimumExposureDurationMinutes` means, but not sure what the other parameters are used for yet. 

This is a country reaching out to another country for guidance on what the latter has learned from the configs. Thus, we would appreciate your insight/guidance on these parameters. Thanks a lot!

**Comment by amarbayar** [comment]
We have tried reaching out to the COVID Shield team (the Shopify volunteers) but we haven't had any luck in getting response. Thus, wanted to reach out to your team.

**Comment by timarney** [comment]
Hi  @amarbayar 

For this app we have what we call a first and second pass filters.  The `.json` config is passed to the framework and acts as first pass (very minimal amount of filtering).  The second pass uses attenuation durations which is where we look for a 15min threshold.

> It might be that the numbers should come from each country's Health Authorities.

Yes this is the case for Canada

**General guidance**
If your looking for general guidance I would suggest the Slack channel on 

Linux Foundation Public Health (LFPH)

https://www.lfph.io/

<img width="500" src="https://user-images.githubusercontent.com/62242/100614126-a1e47100-32e3-11eb-8cfe-a1166e07a21f.png">

**Comment by timarney** [comment]
You can read more about attenuation duration thresholds here:

https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3601128-attenuationdurationthresholds?language=objc

**Comment by amarbayar** [comment]
@timarney - Thanks a lot! These are all great information. Will also join the Slack channel for general guidance. :)
