### ISSUE TITLE
Add support for iOS 12.5 ( iPhone 5s, 6, and 6 Plus)

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-alert-app#1300]
Apple has released iOS 12.5 which includes the Exposure Notifications framework.

https://9to5mac.com/2020/12/14/apple-releases-ios-12-5-for-older-iphones-with-support-for-covid-19-exposure-notifications/

Once updated the app should be able to run on iPhone 5s, 6, and 6 Plus.

**High level updates needed:**
[ ] Set the Deployment Target and Link the Framework
[ ] Perform API and iOS Version Checks
[ ] Set Background Task Interval and Request Runtime to support older iPhones

**Details:**
https://developer.apple.com/documentation/exposurenotification/supporting_exposure_notifications_in_ios_12_5

Ref:
https://github.com/cds-snc/covid-alert-app/issues/1099
https://github.com/cds-snc/covid-alert-app/issues/985

Notes:

> BGTaskScheduler isn’t available in iOS 12.5, Bluetooth explicitly grants apps with the Exposure Notifications entitlement 3.5 minutes at least once a day.

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-alert-app/issues/1099

https://github.com/cds-snc/covid-alert-app/issues/985

**Comment by dsamojlenko** [comment]
Had our first successful exposure test on an iPhone 5S today 🎉 

![image](https://user-images.githubusercontent.com/1187115/102656133-664e0180-4141-11eb-9b4c-863040a804b4.png)

**Comment by timarney** [comment]
Multiple iPhones test 🎉  

<img width="800" src="https://user-images.githubusercontent.com/62242/102692085-0b6ae780-41df-11eb-983b-67802fc2ce1e.jpg" />

**Comment by timarney** [comment]
Further testing has been completed on v6 devices.

A few items remain:

- Finish testing with a second 5s device 
- Error handling for 13.0 -  13.4 devices

> Although iOS 13.0 to 13.4 doesn’t support Exposure Notifications, your app might still download onto devices with those versions of iOS. If that happens, present a dialog to let the user know Exposure Notifications isn’t available for their device.

**Comment by timarney** [comment]
Merged
https://github.com/cds-snc/covid-alert-app/pull/1306
