### ISSUE TITLE
Proximity contact notification

### ISSUE THREAD

**Issue by LeCanardQuoi** [cds-snc/covid-alert-app#1304]
# Summary | Résumé

As a user, I wish to track my proximity contacts and better understand my risks upon an actual occurrence, over and above the currently requested daily log enhancement (#1264). The proposed enhancement is very much of a preventative measure similar to wearing a mask that raises my awareness with an actual retro-action on my mobile. App otherwise very much operates in the dark and drains my battery with little immediate gain, specially in low app adoption environments. This enhancement could substantially contribute to increase the app adoption rate, by making it immediately useful for those interested in such feedback info. This could be done independently of the support of reluctant provincial (or territorial) health ministries such as BC and Alberta. A higher adoption rate would lead to a more useful app allowing better tracking of proximity contacts and increasing likelyhood of a diagnosed user reporting back, which remains the current end goal of the app. Finally the app would remain useful for social distancing functions of Canadians traveling to other countries using this Google/Apple ENS framework. 

# Design detail | Précisions au sujet de la conception

5 or 15 minutes proximity contact notification would be configurable, based on my varying needs and risk exposure. If enabled, a notification would be carried out on my mobile upon a proximity contact 5 or 15 minutes duration. Notif of a new contact would simply include a time stamp flagged in yellow. Reoccurring contact (presumably from my bubble) could be flagged green, or discarded. By default, this notification would not be enabled until explicitly set by user so that behavior of app does not automatically change upon an upgrade.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

This proposed enhancement is somewhat "repurposing" the app (similarly to #1264) with more social distancing capabilities. It is currently expected that the Google/Apple ENS framework provides the app with such info and it can be unbundled to the app user. The proposed enhancement is not expected to infringe on personal privacy (or individual freedom) as it strictly conveys anonymous info (i.e. no key identifier, just a timestamp) reciprocated with the other contact. Yes, the user of the app will be aware that the other user of the app is similarly protected, as it goes with wearing masks. Yes, the user of the app will also be aware that someone in vicinity does not have a mobile (or the app enabled) and may be behaving more carefully in regards to social distancing as a result. Just as if the other person was not wearing a mask. Very preventative overall expected to lessen community transmission and contact tracing burden.

**Comment by timarney** [comment]
Thanks @LeCanardQuoi

This has been brought back to the team for further discussion.  Going to close this issue and will re-open as needed.

**Comment by LeCanardQuoi** [comment]
This issue was brought to your team (independently of this enhancement request process) over one month ago via someone on the team over building social distancing capabilities to increase adoption rate and make app more useful (even in provinces where the health authority was not brought in yet). There has been no follow up to me anyhow. The "team discussion" process seems opaque, is undocumented and does not properly record things imho. Am sceptical closing the ER will move things any faster as xmas break is about to start. Other social distancing enhancement #1264 (entered by someone else) finds itsef in a similar deadlock mode. So does #1305 (#391 server side) on adding FSA in support of assessing performance of app in a given area.

**Comment by LeCanardQuoi** [comment]
As more lethal strains are emerging, an early proximity contact notification triggered at earliest setting available i.e. 5 minutes timer and lower nominal distance threshold should be part of a stronger app response. App users would become more incented to adopt app, as it becomes more important to protecting their health, long before getting the elusive notif, by which time more damage has been done.
