### ISSUE TITLE
User configuration of app with the 3 first digits of postal code

### ISSUE THREAD

**Issue by LeCanardQuoi** [cds-snc/covid-alert-app#1305]
# Summary | Résumé
As a user, I wish to understand how useful is the app in my vicinity to protect each other through the app adoption rate as the main indicator, similarly to wearing masks readily visible. I would be more than prepared to share my 3 first digits of my postal code, a rough geographical indicator of that vicinity. CDS would be expected to somehow report on related meaningful stats and somehow promote in collaboration with local health authorities more actively reaching higher adoption rates.  

# Design detail | Précisions au sujet de la conception
The “Forward Sortation Area” (FSA) 3 first digits in postal code commonly used for similar purposes would be configured alongside the province (or territory) when first setting up the app. Upon the app upgrade, the user would be prompted to provide such info. This info would be conveyed across the server interface for compiling deployment statistics and reported independently of this enhancement request. 

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet
The app/server interface is currently expected to be extendable with such info, similarly to the province for which the app is configured. The proposed enhancement is not expected to infringe on personal privacy (or individual freedom) as it strictly conveys bulk geographical info similarly to the province. The usage of this critical bulk geographical info is beyond the scope of this enhancement. None the less app users should be able to access such meta info on the performance of their app for which their personal public health protection relies. This proposed enhancement would also facilitate field trials concerned with measuring effectiveness of the app -vs- the adoption rate in targeted areas.

**Comment by timarney** [comment]
cc @sidewalkballet

**Comment by timarney** [comment]
Thanks @LeCanardQuoi

This has been brought back to the team for further discussion.  Going to close this issue and will re-open as needed.

**Comment by LeCanardQuoi** [comment]
Note that in NZ GAEN compliant app blessed by privacy commissionner, app usage information is available to everyone (not only health officials). Trust is not only a matter of protecting the privacy of citizens, but also their health. https://t.co/FV7gqOLFZc
