### ISSUE TITLE
Close button is sometimes at the top right

### ISSUE THREAD

**Issue by jsoref** [cds-snc/covid-alert-app#1314]
# Summary | Résumé

> One paragraph explanation of the bug, including why it is a problem (i.e. what does it prevent a user from doing or accomplishing). Screenshots are greatly helpful here too.

The [Material UX guidelines](https://material.io/components/app-bars-top#contextual-action-bar) suggest using an `x` at the top left. But, the enter exposure key flow has a close button at the top right:
![close at top right](https://user-images.githubusercontent.com/2119212/102597993-5efb0980-40e9-11eb-8f64-6eb00397fb18.png)

Most of the close buttons are at the top left, e.g.:
![close at top left](https://user-images.githubusercontent.com/2119212/102598826-97e7ae00-40ea-11eb-9061-5a748e419e02.png)

There's even a cancel button at the top left:
![cancel at top left](https://user-images.githubusercontent.com/2119212/102598102-83ef7c80-40e9-11eb-960b-c69f35714723.png)

# Steps to reproduce | Étapes à reproduire

> Sequential steps (1., 2., 3., ...) that describe how to reproduce the bug. This will help a developer experience what the user experienced so that they can debug it.

1. Open Covid Alert app
2. Tap `Tap for menu`
3. Tap `Enter your one-time key`

# Environment | Environnement logiciel

> What kind of device was the bug experienced with. This would include device, version of the operating system (i.e. iOS or Android), and any other environmental details that might be relevant.

Pixel 3a / Android 11

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

The `Cancel` / `Close` buttons have different vertical padding as well

**Comment by timarney** [comment]
Thanks @jsoref we'll take a look and update accordingly.

**Comment by timarney** [comment]
@amazingphilippe @katewilhelm - can one of you confirm on the design end?

**Comment by amazingphilippe** [comment]
Yes the positioning of the close and cancel actions moves around a bit. The material design guidelines suggest an "X" icon for contextual action bars. However, we are using the top portion of the screen as a navigation bar. Usually to allow users to close a flow, but also sometimes to go back one step in a flow. 

In some cases, the "Close" button does both. It goes back one step and closes the current page. In other cases, the "Close" button closes a multi-step flow from anywhere within the flow. We still allow for users to go back one step with a "back" button. See screenshot:
![8C98797F-D289-4836-83CE-AF120390B199_1_201_a](https://user-images.githubusercontent.com/5230720/109009969-35c49f80-767d-11eb-8bc5-f5d2fd63b24c.jpeg)

Overall, I think you are right to suggest we take a look at the consistency of the position and language of those actions. The last image you provide is a good example where the close button should be on the top right of the screen, if we aim to be consistent.

**Comment by timarney** [comment]
@amazingphilippe has this been accounted for in the latest Figma updates?

**Comment by amazingphilippe** [comment]
> latest Figma updates

Yep! For consistency, we've moved all close buttons to the top right and back buttons to the  top left. In instances where no back button is needed, only the close button remains at the top right.

**Comment by timarney** [comment]
Fixes for iOS went out in a release this morning.

Android will ship possibly Mon.

**Comment by timarney** [comment]
Shipped - closing thanks for flagging @jsoref
