### ISSUE TITLE
Deactivated app still showing exposure check notice

### ISSUE THREAD

**Issue by LeCanardQuoi** [cds-snc/covid-alert-app#1315]
# Summary | Résumé

As a user living in BC (or Alberta), I deactivated my app (in order to minimize battery drain for zero gain) and did notice a day later this message zipping by telling me the app was checking for exposure. It may not be a real problem (as I can just ignore message) but it does not inspire confidence. In addition, I have had no contacts worth checking the exposures for. Seems highly inefficient to check against exposures that were reported in other provinces, certainly when travel is discouraged and people are expected to isolate. Therefore check is draining server and app resources unnecessarily as well.  Worse when app is deemed deactivated. This adds up with millions of users. There should be much better ways to bring app to foreground so it does not hibernate, such as issuing a daily notice on proximity contacts log under #1264. Usefulness of app would also be better demonstrated. Late bug report addition: it was also noticed that the "Last checked for potential exposure" datestamp logged under the Google setting account reporting page did not match the latest check message zooming by, it was in fact 5 days older. 

# Steps to reproduce
Disable app using new menu option. Wait for message to appear. Took a day before I noticed.

# Environment | Environnement logiciel
Android latest app release

# Unresolved questions / Out of scope 
Should there be exposure checks in the first place if there are no proximity contacts whatsoever? Perhaps the exposure check was performed for the period before I deactivated (for which there might have been odd contacts - can't tell since contact daily log not implemented yet)??? It would make more sense to do these checks only when app is activated, or reactivated. Unless you really mean to check on these health worker folks even when they deactivate their app. 

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?
None

**Comment by timarney** [comment]
Hi @LeCanardQuoi thanks for reporting.

We'll look into this as soon as we can.

**Comment by timarney** [comment]
We've been able to recreate this issue (Android) and have started work on a patch.

**Comment by LeCanardQuoi** [comment]
Yes and yes to your previous questions. Android version 9 (LG6). If you are going to fix this for what it is worth, I would suggest to use opportunity to lessen confusion about the protection being provided by including number of proximity contacts being checked alongside number of exposures (Canada-wide) being checked against. If app deactivated as per bug report, it may still be worthwile to report if number of prior proximity contacts is not zero. If app must be brought to the foreground (for obscure "non-hibernation" reasons), an empty flashing message would be less disruptive/confusing imho. Apps rarely flash message to my knowledge. A permanent green message showing number of contacts currently held would be far more useful to users wishing to better understand the protection being provided.

**Comment by timarney** [comment]
Hi @LeCanardQuoi 

Thanks for your comment and yes I should have let you know.

The updates are in Release 1.1.6  

Here's the release notes.

> WHAT'S NEW
- Fixed a bug that showed exposure checks were happening when the app was off. No exposure checks actually happened while the app was off.
- Stopped exposure check message from popping up on screen. The app will still continue to check for exposures.

<img width="550" alt="Screen Shot 2021-01-05 at 1 25 07 PM" src="https://user-images.githubusercontent.com/62242/103684489-a55dbe80-4f59-11eb-8506-2e7c6e142dc5.png">

Issues marked with enhancement are all brought back to the team - we're discussing how we can make that process more open :)
