### ISSUE TITLE
Menu button layout issue with larger accessibility text sizes

### ISSUE THREAD

**Issue by chucks** [cds-snc/covid-alert-app#1317]
# Summary | Résumé

When the iPhone is set to text sizes in the "Accessibility" range, some UI layout is not optimal, particularly the height of the "menu button"

# Steps to reproduce | Étapes à reproduire

Set the system's text size to default, open up COVID Alert. You'll see something like this:
![Standard Size](https://user-images.githubusercontent.com/544380/102821499-2c7d3500-43a5-11eb-90aa-ba4a6d7dfcd2.PNG)

Then set the system text size to something in the "Accessibility" range, here I'm using the smallest of the accessibility sizes `UIContentSizeCategory. accessibilityMedium `

![text Size AX1](https://user-images.githubusercontent.com/544380/102821579-55052f00-43a5-11eb-88df-56f1734b936b.PNG)

Notice how with the larger text size, the menu button at the bottom is not sized sufficiently large for the "tap for menu" text to be visible.

# Environment | Environnement logiciel

iPhone 12 Pro, iOS 14.3
iPhone 6S, iOS 14.2

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

In general, the text sizes used in the app when the system is set to the larger text sizes could use a bit of optimization. Here, you can see the text of Apple's "Body" style in the settings app, for how I have my phone configured:

![Body Text Size](https://user-images.githubusercontent.com/544380/102821760-a01f4200-43a5-11eb-85e0-ab01b98979e9.jpeg)

I would expect the text for "Your phone is now running Bluetooth…" to be set in a comparable size to Apple's body style. The COVID alert text is larger, but at least for how I prefer my phone to be set up, the text is unnecessarily large and this can impact information density. 

![text Size AX1](https://user-images.githubusercontent.com/544380/102821777-a9101380-43a5-11eb-8def-e7e2d71982ab.PNG)

**Comment by timarney** [comment]
@smcmurtry given we're making adjustments to the bottom menu (https://github.com/cds-snc/covid-alert-app/pull/1429)  please see if we can correct this issue as well

**Comment by maryrae-qa** [comment]
Still seeing issue on iOS with large text using the latest release for New Menu items. Screenshots below:

![iPhone 5](https://user-images.githubusercontent.com/76972625/110700060-824fc500-81bd-11eb-9798-5d6d9e70f9cc.PNG)
![iPhone 6s](https://user-images.githubusercontent.com/76972625/110700188-a90dfb80-81bd-11eb-9646-927b5ac15df5.PNG)
![iPhone 6plus](https://user-images.githubusercontent.com/76972625/110700215-b32ffa00-81bd-11eb-8778-5c18b37839df.JPG)

**Comment by timarney** [comment]
Thanks @maryrae-qa 

We're going to make some further adjustments to make this much better using a font multiplier property.

**Comment by timarney** [comment]
Follow up PR in progress

https://github.com/cds-snc/covid-alert-app/pull/1461

**Comment by chucks** [comment]
I'm not sure if I'm the one who should close this, but for my own experience, version 1.2.4 of the app addresses my original issue.
