### ISSUE TITLE
Cross-device data migration feature? | 
Fonction de migration entre appareils?

### ISSUE THREAD

**Issue by sambostock** [cds-snc/covid-alert-app#1322]
# Summary | Résumé

As a user of the app, I want to be able to migrate my  data to a new device, so I can be alerted of (or report) exposures while I was still using the old device.

---

En tant qu'utilisateur de l'application, je veux pouvoir migrer mes données vers un nouvel appareil, afin d'être averti d'exposition (ou de signaler une exposition) durant l'utilisation de mon appareil précédent.

# Design detail

Assuming this is possible using the GAEN system, offering the user the option to copy their recorded (and generated) codes would allow migration from one device to another without gaps in exposure coverage. This could be offered in the settings and transfer data via bluetooth, wifi, qr code, or otherwise. The transfer mechanism should allow transfer across operating systems, if possible (iOS to Android or vice versa).

---

Désolé de n'avoir aucune transcription française des détails! Mon français est trop rouillé. 😅

**Comment by timarney** [comment]
Hi @sambostock 

Unfortunately there's nothing we can do at the app level at this time the GAEN framework doesn't have anything to allow an app to transfer codes phones.

Going to close this but will re-open if that changes in the future.

Reference:
https://twitter.com/CDS_GC/status/1328730487322537984
https://github.com/corona-warn-app/cwa-wishlist/issues/8
https://www.theverge.com/2020/10/26/21535350/iphone-12-pro-covid-19-exposure-notifications-apple

**Comment by maxneuvians** [comment]
Hi @sambostock 👋
