### ISSUE TITLE
Provide for quarantine social distancing notifications

### ISSUE THREAD

**Issue by LeCanardQuoi** [cds-snc/covid-alert-app#1380]
# Summary | Résumé
As a user of the app, I expect to be notified when in the proximity of an other app {or “tokens” #1329) of someone that has been ordered for quarantine so that I can further distantiate, for instance. The most sensitive proximity contact timer of 5 (-vs- default 15) minutes should be used for that notice (#1332). I also expect that people put under quarantine cannot enter a public place protected with QR code support (#1328).  In the event that I am under quarantine order, I expect the app to provide a record of my compliance, and warn me if ever I came in the proximity of others (or others came in my proximity). 

# Design detail | Précisions au sujet de la conception
The app user interface should be enhanced with “Start/End quarantine”. Related events would be logged. Social distancing specified in #1304 and #1332 would be enhanced accordingly. Maintaining the app anonymousness should remain possible. Deactivating the app should not be possible under quarantine. App must be activated before entering a quarantine. Turning off the Bluetooth and the app should be logged as part of this compliance record. 

As far a protecting personal privacy, the app user should be warned that other app users entering quarantine will be notified of a quarantine proximity contact if coming in their vicinity. Similar caveat on #1304.  

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet
This proposed enhancement is tied to several others that have yet to be attended, most importantly related to increasing the app adoption rate, by making it more useful.

It should be confirmed that the app server and health care portal components would not be affected, other than perhaps improved stats reporting #391 (e.g. number of users being quarantined per first 3 digits postal code FSA).

Dealing with more virulent strains will require a stronger response of the app, in support of emerging public policies. App should be quickly revised in accordance to the Ebola pandemic response principle:  "Moving quickly is essential and avoid aiming for perfection before making a move”. Critical leadership will be required, including improved management of new requirements large backlog. https://github.com/cds-snc/covid-alert-server/discussions/417 .

**Comment by CalvinRodo** [comment]
Closing this issue as we currently do not have plans to notify people of anything other than direct exposure with the virus. We cannot track compliance with the app, as that would breach agreements in the GAEN framework, and would impact the current privacy standards we have set. There is no plan to change this.

**Comment by LeCanardQuoi** [comment]
It would be useful to understand the app plan for dealing with more virulent strains of covid-19 and changing public policies requiring a tougher response. Any plans for configurable db level threshold/proximity timer, for new notification types or for increasing app usage other than more messaging/promos? HC, the advisory council and provincial health autorithies should participate in these vital decisions, -vs- the GAEN framework and disclaimers available during public health emergencies.
