### ISSUE TITLE
To do - QR code work

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/covid-alert-app#1402]
# Summary | Résumé

To do list for implementing QR code flow:
- [x] fix layout on the "RequestCameraPermission" screen (Omar)
- [x] fix layout on the "CheckInSuccessful" screen (Steve)
- [x] fix layout on the "InvalidQRCodeScreen" screen, add icon (Omar)
- [x] Fix bug where `CameraPermissionDenied` is displayed after the user grants the permission in settings. Currently it only re-renders after the page is closed and re-opened. (Tim)

**Content/UI**
-  [x] content or view to let user know they have successfully "cancelled checkin"  (TBD) (Omar)
- [x] add push notification to let you know you have been part of an outbreak (Omar)

**ID / token validation**
- [ ] add JSON web token verification to iOS @craigzour 
- [ ] add JSON web token verification to Android @jeberhardt 

**Outbreak Scenario**
- [x] Save outbreak status to an observable, similarly to `ExposureStatus` (Steve)
- [x] Move the "you've been part of an outbreak" to the home screen, put in placeholder content to make it more obvious this is different from the existing exposed screen (Steve)
- [x] add env variable to get outbreak location json from Github (Steve)
- [x] Clear outbreak status button (in the Test menu) (Tim)
- [x] Hook clear button to outbreak status to do the actual clearing (Steve)
- [x] calculations for exposed time periods, tests for this (Steve)
- [ ] add lookup table mapping "location type" to "default dwell time", ~10min (?) for convenience store, longer for other types, etc
- [ ] add "location type" to QR code

**Comment by feralbob** [comment]
What is the proposed format of the proposed QRCode? Is it going to directly model the form of the UK app? 

https://www.revk.uk/2020/09/how-not-to-qr-nhs-c19-app.html

Does it form a URL eg covidalert://somedetails? Just wondering how the default camera behaviour could be used to trigger the automatic loading of the correct app via deep linking vs having to manually start the CovidAlert app. Longer term this makes me wonder about AppClip/InstantApp behaviour which might increase the number of people using the app via those upgrade flows.

**Comment by timarney** [comment]
@feralbob 

covidalert://json-web-token 

The current prototype listens here:
https://github.com/cds-snc/covid-alert-app/pull/1384/files#diff-9f41850eef91746316258be95b41fe45f11e025dbefdfb1f8f3265730246fccbR27

The prototype currently supports "on device" + in app scanning

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Outbreak Scenario Dev Work](https://trello.com/c/YG8KN0l7/1031-outbreak-scenario-dev-work)

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QR Codes: ID / token validation](https://trello.com/c/QDdI3jbw/1032-qr-codes-id-token-validation)

**Comment by feralbob** [comment]
@smcmurtry I don't have access to that Trello board

I've got the qrcode branch 'running' on my iOS device. Looking at everything now - between work and kids etc.
