### ISSUE TITLE
Run app on android 4.4

### ISSUE THREAD

**Issue by ynjacobs** [cds-snc/covid-alert-app#1441]
Hello, thanks for developing this app,

I'm trying to run the app on android studio and am wondering how/if I can run it on android 4.4.

Thanks so much!

**Comment by jose-cds** [comment]
Hey, thanks for your comment! For now, we have not been able to provide support for Android 4.4. Though paused, we did begin work to support Android 5. If you are interested, you can learn more about it here: [cds-snc/covid-alert-app: Pull Request 1333.](https://github.com/cds-snc/covid-alert-app/pull/1333)
