### ISSUE TITLE
Possible simplification of logic in ExposureCheckeSchedulerModule

### ISSUE THREAD

**Issue by dj2** [cds-snc/covid-alert-app#1495]
# Summary | Résumé

In `executeExposureCheck` and `scheduleExposureCheck` we receive a `data` `ReadableMap` which we want to pull notification data out of. Currently the `executeExposureCheck` code does:

```kotlin
val config = data.toHashMap().toJson().parse(NotificationPayload::class.java)
 val workerData = Data.Builder()
    .putString("title", config.title)
    .putString("body", config.body)
    .putString("channelName", config.channelName)
    .putBoolean("disableSound", config.disableSound)
    .build()
```

which produces a class and we read the values out. This seems like it could be simplified to read the data directly from `data` instead of bouncing through JSON. Something like:

```kotlin
val workerData = Data.Builder()
  .putString("title", data.getString("alertTitle"))
  .putString("body", data.getString("alertBody"))
  .putString("channelName", data.getString("channelName"))
  .putBoolean("disableSound", data.getBoolean("disableSound"))
  .build()
```

**Comment by timarney** [comment]
@jeberhardt any thoughts on this ?

**Comment by timarney** [comment]
I like the suggestion but we're going to opt to not to make this update given the app is stable and falling into more maintenance mode at this point.
