### ISSUE TITLE
Inconsistent App version being through metrics

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/covid-alert-app#1517]
Sometimes the app version comes in as a semantic version and other times as a build number, we think this might depend on where the metric is generated (native vs react-native).

It would be more useful for comparison purposes to have this consistent across all metrics.

**Comment by CalvinRodo** [comment]
Please inform server if this fix will happen and when it will go out as we will have to modify our csv generation code.

**Comment by craigzour** [comment]
Do you have an example of a metric payload that contains a build number instead of a semantic version? Having the exact build number would probably help figure out where this is coming from.

**Comment by smcmurtry** [comment]
Below is what I am seeing for app version for each of the metrics identifiers. 
The pattern is this: 
- if the metric comes from react native, we get a build number
- if the metric comes from kotlin, we get a semantic version

```
background-process :  {'268', '289', '275', '265', '286', '252', '246', '247', '233', '248', '281', '278', '267'}
active-user :  {'244', '289', '275', '247', '236', '239', '238', '278', '235', '281', '241', '286', '252', '268', '266', '265', '246', '233', '248', '267'}
otk-entered :  {'268', '275', '281', '278', '267'}
installed :  {'268', '244', '289', '275', '266', '265', '286', '252', '246', '247', '233', '248', '281', '241', '278', '267'}
en-toggle :  {'268', '244', '289', '275', '235', '266', '286', '252', '246', '247', '233', '248', '281', '241', '239', '278', '267'}
otk-no-date :  {'275', '252', '246', '233', '248', '267'}
background-check :  {'268', '244', '289', '275', '235', '265', '286', '252', '246', '247', '233', '248', '281', '241', '239', '238', '278', '267'}
android-package-replaced :  {'1.2.7', '1.2.5', '1.2.4', '1.2.8', '1.2.2', '1.2.3', '1.2.6'}
scheduled-check-started-today :  {'1.2.8'}
otk-with-date :  {'268', '275', '246', '252', '233', '248', '281', '278', '267'}
scheduled-check-successful-today :  {'1.2.8'}
exposed :  {'268', '275', '252', '246', '233', '248', '281', '278', '267'}
onboarded :  {'268', '244', '289', '275', '266', '265', '286', '252', '246', '247', '233', '248', '281', '241', '239', '278', '267'}
exposed-clear :  {'268', '275', '252', '246', '233', '248', '281', '278', '267'}
```

**Comment by craigzour** [comment]
What do we prefer as `appversion`? Looks like it was somehow decided that the React layer would send the build number instead of the real semantic version but I am not sure why. cc @timarney

**Comment by smcmurtry** [comment]
I would prefer the semantic version.

**Comment by timarney** [comment]
Let's update the React layer to use the `real semantic version` i.e. 1.2.8

**Comment by craigzour** [comment]
https://github.com/cds-snc/covid-alert-app/pull/1524

**Comment by craigzour** [comment]
Pull request has been merged and will be part of the next release. cc @CalvinRodo @smcmurtry
