### ISSUE TITLE
Transition to main as the primary branch?

### ISSUE THREAD

**Issue by dj2** [cds-snc/covid-alert-app#1573]
Can we transition this repo to using `main` as the primary branch name? Do we know if there are processes outside of this repository that refer to the branch name? If so, what are they?

**Comment by jeberhardt** [comment]
What's the rationale behind this change? I have no objections, just wondering what's driving the request.

If we're looking at branch names, I would like to see a "Develop" branch, which would be used as described by Gitflow.  https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by dj2** [comment]
Awesome, thank you.
