### ISSUE TITLE
iOS background checks started substantially less then background checks completed.

### ISSUE THREAD

**Issue by dj2** [cds-snc/covid-alert-app#1621]
# Summary | Résumé
With the latest version of the iOS app there were two new metrics added. One for daily background checks started and one for daily background checks completed.

When adding these, we knew there would be a discrepancy between the two values because you can complete exposure checks when not in the background. That said, looking at the data, the completed metric is two orders of magnitude greater than the started metric. That seems like ... a lot.

We need to investigate the metrics and determine if we're missing some of the background check started calls.

**Comment by craigzour** [comment]
I know @jeberhardt wanted to take a look at the https://github.com/transistorsoft/transistor-background-fetch library to see if the way we plugged our `scheduled-check-started-today` metric made sense. As we can see [here](https://github.com/cds-snc/covid-alert-app/blob/97bb1603414043f85b6843e17f8170cbd48452b9/ios/CovidShield/AppDelegate.m#L129) I already proposed an alternative that we could try next.

**Comment by sboots** [comment]
Following (thanks for flagging this @dj2!)

Note that `active-users` is showing significantly lower iOS totals reporting than before the update, not sure if this is a related issue (for example if the iOS active-users totals now coming in are just phones still on previous versions of the app).

**Comment by craigzour** [comment]
Here is a PR to try to solve the `scheduled-check-started-today` < `scheduled-check-successful-today` https://github.com/cds-snc/covid-alert-app/pull/1625

@sboots Could be related but one thing I know for sure is that the implementation for `scheduled-check-started-today` was not fully testable on a developer standpoint and then we did not have time to wait for a week and having QA devices running in staging to make sure it worked. This is also why I did have a Plan B (you can see it in a comment I put in the code if you look at the PR changes).

**Comment by craigzour** [comment]
PR has been merged :)

**Comment by timarney** [comment]
@dj2 anything further here?

**Comment by dj2** [comment]
I believe we just need to wait for the release rollout to see if the numbers make sense.

**Comment by timarney** [comment]
Now?
