### ISSUE TITLE
Awkward English

### ISSUE THREAD

**Issue by jsoref** [cds-snc/covid-alert-app#1661]
Skimming the actual flow in https://github.com/cds-snc/covid-alert-app/pull/1624#issue-652733411...

## Public Health

Sometimes it's a proper noun:
https://github.com/cds-snc/covid-alert-app/blob/3cdc39ea813a2819513ef1e5af433e0bb0c91069/src/locale/translations/regional/en.json#L21

Sometimes it isn't:
https://github.com/cds-snc/covid-alert-app/blob/3cdc39ea813a2819513ef1e5af433e0bb0c91069/src/locale/translations/regional/en.json#L28

I'd suggest in English that it always be written as a proper noun (`Public Health`).

(I'm not going to cite all instances, and I won't even include that change below.)

## Ordered

https://github.com/cds-snc/covid-alert-app/blob/bad291571970ca7c7c79633891b65676de59148d/src/locale/translations/en.json#L584

`ordered` is a technical term, and can be confusing, because in the context of COVID and Testing, it could mean:
1. mandated (by public health, as in "Public Health ordered you to quarantine")
2. scheduled (as in "the doctor ordered a test")
3. sorted (as used here)

I'd suggest:
```diff
- "Body": "Your exposures are ordered based on the date of notification.\n\nExposures are deleted after 14 days.",
+ "Body": "Your exposures are listed based on the date of notification.\n\nExposures are deleted after 14 days.",
```

## If/When / conditional

https://github.com/cds-snc/covid-alert-app/blob/3cdc39ea813a2819513ef1e5af433e0bb0c91069/src/locale/translations/regional/en.json#L98

1. `If` should be `When`
2. `gives` should probably be `will give`
3. `along with`  should probably just be `with`

```diff
- "Body": "If you test positive for COVID-19, public health gives you a one-time key along with your positive test result.\n\nYou will only get one key, and it expires in 24 hours.",
+ "Body": "When you test positive for COVID-19, public health will give you a one-time key with your positive test result.\n\nYou will only get one key, and it expires in 24 hours.",
```

## This/The app

https://github.com/cds-snc/covid-alert-app/blob/70eb5d8186a27efb6db9ae16011b53aefc4ae242/src/locale/translations/en.json#L19

This message uses both `this app` and `the app`, you should determine how to self-reference and use it consistency (I'd suggest `this app`):

```diff
- "AllSetBody": "In some provinces and territories, people cannot yet report a COVID-19 diagnosis through this app.\n\nChoose your area from the menu to find out if it supports the app."
+ "AllSetBody": "In some provinces and territories, people cannot yet report a COVID-19 diagnosis through this app.\n\nChoose your area from the menu to find out if it supports this app."
```

Again, I'm not flagging all instances.

I'll include one other just to highlight it:
https://github.com/cds-snc/covid-alert-app/blob/70eb5d8186a27efb6db9ae16011b53aefc4ae242/src/locale/translations/en.json#L41

Using `the` here hints that it's documentation about some hypothetical event that may occur. But based on the picture
![picture of the alert](https://user-images.githubusercontent.com/33768337/119875885-480cde80-bef5-11eb-82f4-849dcc1f8592.png)
it appears that this _is_ the alert, and thus it should say `this alert`.

### For your (preposition)

https://github.com/cds-snc/covid-alert-app/blob/70eb5d8186a27efb6db9ae16011b53aefc4ae242/src/locale/translations/en.json#L367

I'm not quite sure how formal this app is trying to be, but, while one might informally say "will ask your permission", formally one would write "will ask _for_ your permission" (at least in `en-US`, I've only been in Canada for a decade, so I could be wrong about `en-CA`).

```diff
- "Body1": "Your phone will ask your permission to upload your most recent random codes or “random IDs”.\n\n**Exposed people will not get any information about you** or the time you were near them.",
+ "Body1": "Your phone will ask for your permission to upload your most recent random codes or “random IDs”.\n\n**Exposed people will not get any information about you** or the time you were near them.",
```

---
Fwiw, years ago I wrote a tool to analyze translations and detect issues like these.

**Comment by sidewalkballet** [comment]
Thanks for the review and the comments! Tagging in @EliseKa for consideration.

**Comment by EliseKa** [comment]
Thanks for the review! We're happy to make some of the changes, and we'll add those to our backlog to prioritize.

About the bits we'll keep as they are:
- We won't change "if" for "when" because people who look at that screen might never have covid.
- We'll keep "public health" or "Public Health" as they are. The lowercase form is not ambiguous and is widely used elsewhere. In some cases, Public Health might not be the proper noun since the name changes across the country. Some of the instances appear in regional content, meaning the preference could come from the provinces/territories. But thanks for noting that, we'll add a layer of proofing for consistency next time :) 
- We'll keep "ask permission" since it's more conversational.
