### ISSUE TITLE
Does not work, claims not installed on main profile. Other covid trace apps works.

### ISSUE THREAD

**Issue by simplerick-simplefun** [cds-snc/covid-alert-app#1735]
COVID Alert app does not work on my phone.
During setup, the last step shows "Something went wrong....try installing app in the main profile".
I have verified that the app is indeed installed on the main profile. It is installed using google play store.
My phone is Oneplus 7 pro, running android 11.
I tested ABTraceTogether app on my phone and it works fine.
See screenshots for details.
Let me know if more info is needed. 
![Screenshot_20210713-013710](https://user-images.githubusercontent.com/13503950/125333345-ba8a2e80-e37c-11eb-9ccf-09332b153e50.jpg)
![Screenshot_20210713-013732](https://user-images.githubusercontent.com/13503950/125333346-ba8a2e80-e37c-11eb-9174-ded947cb37ea.jpg)
![Screenshot_20210713-014307](https://user-images.githubusercontent.com/13503950/125333349-bb22c500-e37c-11eb-928f-4e64a7781da3.jpg)
![Screenshot_20210713-014710](https://user-images.githubusercontent.com/13503950/125333351-bb22c500-e37c-11eb-891e-ccf50aa39815.jpg)
![Screenshot_20210713-014917](https://user-images.githubusercontent.com/13503950/125333354-bb22c500-e37c-11eb-9ebd-a63cbd953205.jpg)

**Comment by timarney** [comment]
What do you see under 

Settings > Google > Covid-19 Exposure Notifications  ?

<img width="750" alt="Screen Shot 2021-07-12 at 6 00 14 PM" src="https://user-images.githubusercontent.com/62242/125361302-2186f380-e33b-11eb-9ec8-ff9ff41f8ca1.png">

**Comment by dangelization** [comment]
It does not have the “COVID-19 Exposure Notifications” part under Settings > Google.

**Comment by timarney** [comment]
In which case this is a phone level / OS level issue vs something wrong with the app.

I'll reach out to our support team and see if they've seen anything similar.

In the meantime here's a few Google support links. 

https://support.google.com/android/answer/9888358?hl=en#zippy=

https://support.google.com/android/answer/7680439

**Comment by jeberhardt** [comment]
Closing since the project is retired.
