### ISSUE TITLE
Add Proof of Vaccination

### ISSUE THREAD

**Issue by ikifar2012** [cds-snc/covid-alert-app#1736]
# Summary 

Allow us to add/upload proof of vaccination to the app, originally suggested by Jean Yoon on Twitter 
https://twitter.com/jean_yoon/status/1420500247873261575

---

# Design detail 

A virtual vaccination card that would be available both in the app and in Apple Wallet would be a great way to display this information as Apple Wallet supports both the iPhone and Apple Watch 

---

**Comment by jeberhardt** [comment]
Closing since the project is retired.
