### ISSUE TITLE
Closing Android app when Bluetooth is disabled deactivates exposure notifications 

### ISSUE THREAD

**Issue by krutkay** [cds-snc/covid-alert-app#1737]
# Summary

The COVID Alert app on Android can silently deactivate when Bluetooth is disabled on the phone, even if Bluetooth is later re-enabled.  The user is not notified that COVID Alert has been "permanently" disabled.

# Steps to reproduce

https://user-images.githubusercontent.com/4410775/129608126-dc3e80f2-0b88-4e92-b16d-904393ed3c33.mp4

1. Open COVID Alert and ensure app exposure detection is active.
2. Turn off Bluetooth.
3. Observe that the COVID Alert app UI shows that "Bluetooth is off" and reminds the user that they need to turn Bluetooth on for COVID Alert to work.
4. Close the COVID Alert app using the Android task switcher ("swipe" it closed, don't just return to the home screen).
5. Re-open the COVID Alert app.
    - **Issue**: the app will ask if you want to turn on COVID-19 exposure notifications.
    - **Expected behaviour**: the app should show the same screen as in Step 3.
6. Return to the home screen.
7. Enable Bluetooth.
8. Re-open the COVID Alert app.
    - **Expected behaviour**: the app should be "enabled" and should show the same screen as in Step 1.

# Environment

Running COVID Alert v1.5.3.
Found on a Pixel 3 running Android 11 (Build number RQ3A.210805.001.A1 / August 5, 2021 security update)

**Comment by Thanayaby** [comment]
What whynbc

**Comment by Thanayaby** [comment]
Til

**Comment by jeberhardt** [comment]
Closing since the project is retired.
