### ISSUE TITLE
 MOB-H-4: Android Key Material Stored in Insecure Fashion

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#435]
**Vulnerability Summary**
The Android mobile application key material is stored unencrypted within the applications directory. This exposes the keys to an unnecessary level of risk.
Classification:
• OWASP: M2: Insecure Data Storage
• OWASP: M5: Insufficient Cryptography
• OWASP: M7: Client Code Quality

**Analysis of the Attack**
The Android mobile application stores the applications private key unencrypted within the applications ‘shared_preferences.xml’ file. This key is used as part of the communications exchange between the application and server when submitting the Exposure Notification API data.
An adversary would have to compromise the device to retrieve the key material, but they would then be readily available with no additional compensating controls.

**Recommendation**
The Android application should leverage the keystore system through the KeyChain API. This mechanism provides a secure means of storing and processing sensitive key material.
Official documentation is provided at https://developer.android.com/training/articles/keystore.

**Comment by obrien-j** [comment]
Similar issue/comments to #434

**Comment by jeberhardt** [comment]
We would need to either modify `react-native-sensitive-info`, the current package we are using, or replace the functionality with something that specifically uses Android Keystore. At the moment, `react-native-sensitive-info` uses a key to encode the data, but it's still stored in Shared preferences, and that's only on devices that support TouchID.

This might be a suitable replacement: https://github.com/pradeep1991singh/react-native-secure-key-store

**Comment by obrien-j** [comment]
https://github.com/mCodex/react-native-sensitive-info/tree/keystore <-- the existing implementation appears to have a keystore branch, no statement of 'fit for purpose'. 

Safe to assume this would require another OS prompt for to access they keystore yes?
