### ISSUE TITLE
MOB-M-1: Default Hardcoded HMAC Key

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#438]
**Analysis of the Attack**
Blackberry note the default environment settings file contain a hardcoded HMAC key string. It is common pattern to see default values changed, therefore this may result in “insecure by default” deployments.

**Recommendation**
• Do not provide a default value for items that require entropy
• Ideally generate these values within provisioning scripts
• Ensure guidance is provided within the documentation on the critical nature of the value and
how it should be managed. This may include references to secret material management service APIs.

**Comment by timarney** [comment]
@obrien-j any suggestions here?

The HMAC is in the .env file and gets pulled into the app.

**Comment by obrien-j** [comment]
Works for me.
