### ISSUE TITLE
MOB-M-3: iOS Application Caches HTTPS Requests/Responses

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#440]
**Vulnerability Summary**
iOS stores application HTTP requests and responses on disk in an unencrypted format by default. These requests may contain sensitive data, such that the user has been diagnosed with Covid-19.

**Analysis of the Attack**
Blackberry noted that the iOS application does not prevent HTTP requests and responses from being cached.
Requests made using ‘NSURLRequest’ will cache responses in the Cache.db file within the applications container. This cache file is kept unencrypted within the applications container directory on disk. Sensitive HTTP requests made through the application may indicate that the user has been diagnosed with Covid-19.
An adversary would have to compromise the device to retrieve the snapshots. However, there is scope for diagnosis information to be consider personal health information (PHI) and therefore it should be afforded with industry recommended security protections.

**Recommendation**
• Set the ‘cachePolicy’ property of ‘NSURLRequest’ to disable the caching of HTTP/S requests and responses
• (NSCachedURLResponse)connection:(NSURLConnection)connection
 willCacheResponse:(NSCachedURLResponse *)cachedResponse { return nil;
• Follow offical Apple guidance provided at https://developer.apple.com/documentation/foundation/url_loading_system/accessing_cache d_data

**Comment by jeberhardt** [comment]
Looking to see if there's a React-Native solution for this, or if the solution needs to be iOS specific.

**fetch** does allow for headers to be set, and can use **{cache:'no-store}**.

**Comment by jeberhardt** [comment]
Re-opening since the PR was reverted.

**Comment by obrien-j** [comment]
Reopening as this was only fixed in RN.fetch , dropping to lowpri and removing v1launch until we can adequately confirm whether we want to cache the specific data being downloaded, which I believe is only downloaded diagnosis keys currently.

tangent: caching these keys would allow for potential interesting 'multi-jurisdisction exposure checks with different exposureconfiguration elements'.
