### ISSUE TITLE
MOB-M-4: Android Application Caches HTTPS Requests/Responses

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#441]
**Vulnerability Summary**
The Android HTTP library allows requests and responses to be cached to disk. This mechanism uses an unencrypted format by default. These requests may contain sensitive data, such that the user has been diagnosed with Covid-19.

**Analysis of the Attack**
Blackberry noted that the Android application does not prevent HTTP requests and responses from being cached.
HTTP/S request and responses made by the application are cached within plain-text files within the applications directory. Sensitive HTTP requests made through the application may indicate that the user has been diagnosed with Covid-19.
An adversary would have to compromise the device to retrieve the snapshots. However, there is scope for diagnosis information to be consider personal health information (PHI) and therefore it should be afforded with industry recommended security protections.

Recommendation
Figure 37: Snippet of HTTPS response stored on disk
• Use ‘HttpsURLConnection’ with ‘setUseCaches(false)’
• Ensure the web application front edge sets the "no-store" directive in a response header (cc: @maxneuvians )

**Comment by obrien-j** [comment]
Marking as Medium as this assumes full device compromise, which is likely a bigger problem.

Relatively easy fix though so will aim to get it fixed shortly.

**Comment by jeberhardt** [comment]
Re-opening since the PR was reverted.

**Comment by obrien-j** [comment]
reopening as fix was only to RN.fetch, not okhttpclient.

Noting, this needs review to determine when/where we actually want to disable caching.
