### ISSUE TITLE
Error code 10 when calling detectExposure on Samsung Tablet

### ISSUE THREAD

**Issue by henrytao-me** [cds-snc/covid-alert-app#593]
Tablet: wait for exposed notification => never receive. Some issue with the framework. It's return error code 10 when calling detectExposure https://sentry.io/organizations/canadian-digital-service/issues/1774528672/?project=5309250&query=device%3A%22SM-T387W%22.

## Environment: 
Samsung Galaxy Tab A - SM-T387W - Android 9. 

![image](https://user-images.githubusercontent.com/5274722/87153507-984f6380-c285-11ea-9c91-e7ff39762b7f.png)

**Comment by henrytao-me** [comment]
## Report: 
- I couldn't find related thread mentioning about Error Code 10. 
- I ask @dsamojlenko to build me a debug build so that I can see more logs in Android Studio but the debug build doesn't work for non whitelisted developer. I receive Error Code 17 with debug build which is `API_NOT_CONNECTED`. 
- This is a tablet and the first time I see Error Code 10. 

We can revisit later. I think it is less important for launch. 

cc @timarney

**Comment by timarney** [comment]
Will revisit this one later.

**Comment by timarney** [comment]
@henrytao-me anything to follow up on here?

**Comment by henrytao-me** [comment]
## Action item for this issue:

No action

## Explain what happen:

#### Context:
- This error is Android only. 
- Below is the error code list from the framework
```
  public static final int SIGN_IN_REQUIRED = 4;
  public static final int INVALID_ACCOUNT = 5;
  public static final int RESOLUTION_REQUIRED = 6;
  public static final int NETWORK_ERROR = 7;
  public static final int INTERNAL_ERROR = 8;
  public static final int DEVELOPER_ERROR = 10;
  public static final int ERROR = 13;
  public static final int INTERRUPTED = 14;
  public static final int TIMEOUT = 15;
  public static final int CANCELED = 16;
  public static final int API_NOT_CONNECTED = 17;
```
- Error code 10 is `DEVELOPER_ERROR`.

#### What happening:

This exception happens when the app calls any methods from Exposure Notification framework when Exposure Notification permission is OFF. Android bridge catch the exception and throws it back to js layer. The app doesn't crash because we try catch it gracefully. 

## What could be done?

There are two method that we are using to access Exposure Notification framework: `updateExposureStatus ` and `updateExposureStatusInBackground `. We could add this if statement at the beginning of `updateExposureStatus`. 

```ts
    if ((await this.exposureNotification.getStatus()) !== Status.Active) {
      return;
    }
```

This will prevent calling any exposure methods when status is not Active. 

Pros:
- Save a couple of round trip to server to get config / download keys.
- Reasonable to do.

Cons:
- May have unforeseen side effects especially we are launching now.

## Will it affect user if we do nothing? 

No. The app catches this exception already and won't cause any problem.

## What's about iOS? 

TBD
