### ISSUE TITLE
Exposure detected when device is exposed less than 15mins  (iphone XR/iphone 8)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-alert-app#695]
device 1: iPhone 8
positively diagnosed 
device 2: iPhone XR
COVID Exp = ON
Notifications = ON
Bluetooth = ON
UUID= 4Nm9mXAyYrs=

July 13 exposed device 2 to device 1 
**3 feet apart, 10 min exposure**

Device 2: 
July 14 no push notifications displayed on home screen of phone
in app: home screen = You're all set
COVID Exposure checks - last updated July 13 at 246pm 20x
updated app to version 47 - app now shows No exposure detected message.

Checked COVID Exposure checks at 1015am and no new exposure checks 
July 14 at 251pm iPhone screen shows You've been exposed push notification.
COVID Exposure checks shows 251pm has 1 matched key.

Expected behaviour: no exposed state should have been triggered. Less than 15 mins contact.

**Comment by JuliannaR** [comment]
@emilykuret we are now following the expected results doc. Can you confirm if we have sped anything up for testing before we dig to deep here?

**Comment by timarney** [comment]
@jeberhardt can you comment on this?

**Comment by jeberhardt** [comment]
It's a cumulative exposure for the course of the day. If the phones were close to each other for a few moments during parts of the day outside of the 10 minute test window, then those times may push the exposure beyond the 15 minutes.

Is that scenario a possibility?

**Comment by emilykuret** [comment]
We are testing all configurations - will close and conduct testing.
