### ISSUE TITLE
Improve onboarding flow

### ISSUE THREAD

**Issue by henrytao-me** [cds-snc/covid-alert-app#722]
There are a couple of problem with current onboarding flow. In term of user experience, the app is laggy at the end of onboarding flow when EN framework shows consent dialog. 

- Expect: 
  + The consent dialog shows after pressing `Next` in `The app will now ask your permission` screen. 
  + Carousel stays at `The app will now ask your permission` screen until the consent dialog is closed. 
  + Carousel moves to next screen. 

- Actual:
  + The consent dialog shows during carousel transition between `The app will now ask your permission` and next screen. 
  + App is laggy. 

Another related problem which needs UX is that: we cannot stop people swiping to next screen when they are at `The app will now ask your permission`. In order to fix this problem, I suggest to split current onboarding flow into two parts: 
  - 1st part is stopped at accept / deny EN consent dialog.
  - 2nd part is region picker.

So it will look like this: 
> Onboarding carousel > Optional region picker / another carousel (if we have more screen) > Home screen

**Comment by timarney** [comment]
Ref: https://github.com/cds-snc/covid-shield-mobile/issues/709

**Comment by timarney** [comment]
Removing v1launch tag

Considering this to be an optimization vs a blocker 

cc: @emilykuret

**Comment by timarney** [comment]
Noting:

https://github.com/cds-snc/covid-shield-mobile/issues/411#issuecomment-659515478

**Comment by emilykuret** [comment]
Believe this has been fixed. Will revisit if we need to.
