### ISSUE TITLE
App should not show EN consent dialog automatically when reopen

### ISSUE THREAD

**Issue by henrytao-me** [cds-snc/covid-alert-app#723]
## What?

App show EN consent dialog automatically when reopen after EN is disabled in Google Settings. 

## Steps to reproduce
- Pass onboarding flow with EN is enabled. 
- Close the app. 
- Go to Google Settings, disable EN. 
- Reopen the app.
- Expect:
  + EN consent dialog doesn't open because we have UI for that.
- Actual:
  + EN consent dialog opens automatically.

**Comment by emilykuret** [comment]
Hey Henry! I can't recreate this on my Pixel with V53. 

Em

**Comment by timarney** [comment]
We'll review this next week.

**Comment by emilykuret** [comment]
@jeberhardt thinking this ties into the bluetooth work that you're tackling right now.

**Comment by timarney** [comment]
Closing this will re-open as needed.
