### ISSUE TITLE
Exposure detection rate not the same on Android vs iPhone 

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-alert-app#730]
device 1: OnePlus 3 Android v8 OS v49 (English OS)
device 2: iPhone XR iOS v50 (French iOS)
both devices: 
COVID Exposure Notifications = On
Notifications = On
Bluetooth =On
(Test Case 26)

July 15: Exposed both devices to a +diagnosed device (iPhone 8) for more than 15 mins each roughly 3 feet apart.
Exposure was done roughly at the same time (+/- 5mins)

July 16: 
633 am checked the phones - no notifications both devices showed You're all set.

916am iPhone XR rec'd push notification for possible exposure.
OnePlus 3- no push notifications and home screen shows You're all set.

1024 am checked no notifications, no new checks for exposure either (last one was July 16 633 am)
1256 pm rechecked the OnePlus 3 and still not notification ... You're all set is still displayed. 
COVID Exposure Checks were verified and it had a few for July 16th 1027 am x2, 1157 am, 1245 pm x2 and again at 1251 pm - none of these checks have any keys shared or matched keys.

Expected behaviour: both devices should have rec'd the notification at roughly the same time.

**Comment by JuliannaR** [comment]
@emilykuret do we have any data on this? I would think that it would be okay for these to not perfectly align given that are using different frameworks, even if its the same layer between the server?

**Comment by mmiron-HC** [comment]
Update: OnePlus3 rec'd push notification July 17th at 751am. You are exposed message is displayed (updated Android version to 53 on July 16 @ 255pm)

**Comment by emilykuret** [comment]
Retesting all configurations - closing this issue.
