### ISSUE TITLE
Exposure detected at 8ft apart for more than 15 mins (Android version 9) app v53

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-alert-app#747]
(test case 31)
device 1: iphone 8 +diagnosed.
device 2: Samsung Galaxy S8 OS v9 app v53 (UUID: Mm_s8-17)
COVID 19 Exposure notifications = On
Bluetooth = On
Notifications = on

July 15: device 2 was exposed to device 1 at more than 8ft for more than 15 mins
July 16: no exposure detected/COVID checks were being done. Upgraded app to version 53 @ 249pm
July 17: 625 am, no push notifications / no exposure detected (app running in background) no COVID19 checks for July 17
closed app, reopened. 
home screen displays You've been exposed 
COVID Checks for 626 am shows 1 key provided and 1 matched key

Expected behaviour: no exposure detected

**Comment by timarney** [comment]
@jeberhardt ☝️

**Comment by mmiron-HC** [comment]
this phone is currently at 63% not sure what it was at exposure.

**Comment by henrytao-me** [comment]
> Exposure detected at 8ft apart for more than 15 mins

This sounds expected to me. May I know why do we expect `no exposure detected` in this case?

**Comment by mmiron-HC** [comment]
@emilykuret 
as requested, repeated similar scenario July 28
iPhone SE iOS 13.6 app version 66
exposed to +diagnosed XR for 30 mins at 16ft.
July 29 rec'd push notification at 925am that I was exposed.

**Comment by timarney** [comment]
@emilykuret @mmiron-HC can re-test and or close this out?

**Comment by emilykuret** [comment]
Exposure configurations are being rested - closing this.
