### ISSUE TITLE
The app should prioritize exposureSummary by daysSinceLastExposure rather than the most recent check

### ISSUE THREAD

**Issue by henrytao-me** [cds-snc/covid-alert-app#803]
## What?

If the app is in `exposed` state, it uses `daysSinceLastExposure` to clean up the state back to `monitoring` when `daysSinceLastExposure` is more than 14 days. However, the app should prioritize exposureSummary by daysSinceLastExposure rather than the most recent check. 

For instance:
- Phone A was in close contact with phone B 2 days ago who submitted their keys to server yesterday.
- Phone A was in close contact with phone C 10 days ago who submitted their keys to server today.

=> In this case, the app should keep exposureSummary from phone B and ignore phone C because phone B is most recent contact.

## Related issue:

`daysSinceLastExposure` cannot be used for calculating time to reset back to monitoring state because `daysSinceLastExposure` is returned from EN framework as part of exposure summary and never changes. We need to find a way to retrieve lastExposureTimestamp instead. There are two options:
- Option 1: do in js layer. This bases on assumption that EN framework will return exposure summary within the same day of the request. If so, `lastExposureTimestamp = today() - daysSinceLastExposure`. 
- Option 2: do in native layer. Before feeding TEKs to the framework, the native layer should store current timestamp somewhere and retrieve it later. The timestamp could be combined with token on Android (iOS TBD). 

## Action items:
- [x] Add `lastExposureTimestamp` via js layer as it's an okay approach. 
- [ ] Change `lastExposureTimestamp` to use native layer as a follow up PR.

**Comment by henrytao-me** [comment]
Reopen for a follow up PR

**Comment by timarney** [comment]
@henrytao-me anything further one this?

**Comment by emilykuret** [comment]
Closed - will reopen as needed.
