### ISSUE TITLE
One time key field allows for special char and more

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-alert-app#839]
Environment :
Pixel 3a, Android 10, v62

Scenario :
- Navigate to the "Enter a one time key" screen
- In the key field, enter special characters, even emojis, copy-paste content...

Expected :
The field should only allow alphanumeric characters

Issue : 
The field currently allows for all types of content to be entered

![Screenshot (Jul  22, 2020 08_22_36)](https://user-images.githubusercontent.com/47008295/88195485-f4ef3e80-cbf4-11ea-8fb5-b10fdfae6e86.png)

**Comment by mmiron-HC** [comment]
was able to reproduce with iPhone XR.

**Comment by timarney** [comment]
Closing this - we have a PR in but need to handle some more cases.
