### ISSUE TITLE
Non text contrast issues related to nav elements, arrow for expanding menu, and thin line for separating element for back/next

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-alert-app#842]
**Google Play Console Firebase Accessibility finding:**

The item's text contrast ratio is 1.16. This ratio is based on an estimated foreground color of #FFFFFF and an estimated background color of #EEEEEE. Consider using colors that result in a contrast ratio greater than 4.50 for small text, or 3.00 for large text.

Issue:
<img width="973" alt="Screen Shot 2020-07-22 at 11 20 37 AM" src="https://user-images.githubusercontent.com/35537308/88207310-94282c00-cc1d-11ea-8f2d-6e5268e531aa.png">
<img width="870" alt="Screen Shot 2020-07-22 at 11 20 47 AM" src="https://user-images.githubusercontent.com/35537308/88207317-97231c80-cc1d-11ea-9567-5eb316c4fa2c.png">

**Design consideration:**
<img width="1423" alt="Capture d’écran, le 2020-07-22 à 12 16 54" src="https://user-images.githubusercontent.com/35537308/88207287-8f637800-cc1d-11ea-9c21-5e6d8d7c66a3.png">

**Comment by JuliannaR** [comment]
@amazingphilippe I updated the issue here. let me know when you are ready/need to have some support re: dev working on this.

**Comment by amazingphilippe** [comment]
I've got a partial fix in my local version. Assigning myself
