### ISSUE TITLE
Autofocus stealing focus from the push notification permission popup

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/covid-alert-app#845]
When arriving at the home screen after onboarding on a fresh install, the push notification permission popup is shown. Focus moves to this popup, but then moves via our auto focus to the home screen behind. At that point it is no longer possible to get back to the popup using forward/back navigation.

https://youtu.be/E1G9F11vgB8

**Comment by timarney** [comment]
Ping @smcmurtry

**Comment by timarney** [comment]
Steve closing this - re-open as needed.
