### ISSUE TITLE
Explore Solutions for Anonymous Usage Data Tracking

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-alert-app#848]
We will explore solutions for measuring the efficacy of the solution. 

Outcome: 
We have aggregate data on how many time an event has occurred each day (ie. How many phones when into and exposed state?)

Acceptance Criteria
- The data is aggregated and completely anonymous.
- We know how many times each usage event occurred per day. 
- This data can be used in reporting.
- Only store data that we can verify has been sent by the app.

Why we need this: 
For the app to have the intended impact on slowing the spread of COVID-19 it relies on users of the app taking actions in the app, such as turning on EN logging, uploading their keys and viewing guidance after an exposure. We need data on how the app is being used so that can evaluate how effectively the solution is leading users to the correct actions. We will use the data to measure the effectiveness of the app and the impact of improvements we make to get more users to take the correct actions.

**Comment by lchski** [comment]
To give an update on this:

**Comment by lchski** [comment]
This is an exploratory/placeholder issue – we’re still figuring out what this’ll mean, how it’ll work, what it’ll look like, and so on.

One other acceptance criterion I’d raise, to our overall goal of transparency, would be “This data collection is communicated to people using the app.”

Some points on that:

- We won't merge functionality enabling this until the app clearly explains what's happening.
- This would include, at a minimum, changes to the privacy notice, but there may be other pieces (content and interface) that are updated, too.
- We want to make sure people understand what's collected and why it's collected, so they provide informed consent when using the application.

We're still determining how this will work, and will update our public documentation to describe it further once we have the details confirmed.

**Comment by timarney** [comment]
Closing this will re-open as needed.
