### ISSUE TITLE
Content feedback for onboarding, privacy policy and menu

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-alert-app#857]
Content suggestions and considerations

<img width="545" alt="Screen Shot 2020-07-23 at 11 11 19 AM" src="https://user-images.githubusercontent.com/35537308/88308226-cb104780-ccda-11ea-99cf-d32543c5788c.png">
<img width="543" alt="Screen Shot 2020-07-23 at 11 12 29 AM" src="https://user-images.githubusercontent.com/35537308/88308245-d1062880-ccda-11ea-838a-e152c4fe9add.png">
<img width="553" alt="Screen Shot 2020-07-23 at 11 13 54 AM" src="https://user-images.githubusercontent.com/35537308/88308270-da8f9080-ccda-11ea-9c1d-41469e9e3a33.png">
<img width="549" alt="Screen Shot 2020-07-23 at 11 15 26 AM" src="https://user-images.githubusercontent.com/35537308/88309908-014ec680-ccdd-11ea-924b-3b68de9b5eb4.png">
<img width="554" alt="Screen Shot 2020-07-23 at 11 11 47 AM" src="https://user-images.githubusercontent.com/35537308/88309923-0a3f9800-ccdd-11ea-9578-25c4fb62e919.png">

@katewilhelm this one is for you to decide on the best approach.

**Comment by timarney** [comment]
@katewilhelm @JuliannaR can you comment and or close this?

**Comment by timarney** [comment]
Going to close this as we can re-open as needed.
