### ISSUE TITLE
Turning on EN does not turn on BT

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-alert-app#863]
Environment : 
iPhone 8, iOS 13.6, v64

Scenario : 
1. Install the app for the first time without Bluetooth on
2. Navigate through all of the Onboarding screens until the 'Where do you live? (optional)' screen is displayed
3. Verify that the 'Turn on COVID-19 Exposure Notifications' popup is displayed.
4. Click Turn on / Autoriser
5. From the 'Where do you live? (optional)' screen, select Ontario and click Done
7. Verify that the Home page displays 'You're all set" and that a message indicating that Bluetooth is running is displayed. 
8. Verify the bottom of the screen indicates that COVID Alert is active

Issue : 
COVID Alert is off and BT stayed off even after enabling EN at the installation popup

**Comment by emilykuret** [comment]
Closed - will revisit if needed.
