### ISSUE TITLE
publish app for Android on fdroid

### ISSUE THREAD

**Issue by nutpantz** [cds-snc/covid-alert-app#893]
Large numbers of people who do not use Google play and Google play services cannot access this app
It should be published on fdroid or have a download available of the apk.

**Comment by ajayyy** [comment]
This uses the Apple/Google COVID exposure API. That requires google play services.

**Comment by timarney** [comment]
Thanks @ajayyy 

> This uses the Apple/Google COVID exposure API. That requires Google play services.

https://developers.google.com/android/exposure-notifications/exposure-notifications-api

**Comment by sbuller** [comment]
It looks like MicroG has now implemented support for the exposure notification. There are now users that could benefit from a release on F-Droid. Could you guys have another look at this?

**Comment by TheEvilSkeleton** [comment]
@sbuller have you tried creating a custom repository for it? Repomaker is unfortunately deprecated, but you should be able to still create repositories. There is an easy way to install it as Flatpak: https://gitlab.com/fdroid/fdroid-repomaker-flatpak#install-latest-dev-flatpak

**Comment by cmonagle** [comment]
Note that the German "Corona Warn" app (using the same framework) is making progress on F-Droid inclusion.
https://gitlab.com/fdroid/rfp/-/issues/1387
