### ISSUE TITLE
BVC-143 Concurrency Control issue - Access to exposure status is not properly synchronized

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#896]
Access to the exposure status in ExposureNotificationService class is not properly synchronized and could lead to data corruption issues where one thread may update this value while another thread is in the middle of executing a particular function that relies on the previous value of the variable.

The ExposureStatus type is used to keep track of the state of the user's exposure with other related information.
There are currently three possible states (refer to as types in the data structure): 'monitoring', 'exposed' and 'diagnosed'

An instance of the ExposureStatus type is stored within the ExposureNotificationService class which is responsible for:

 periodic processing of diagnosis file downloads and exposure matching via the performExposureStatusUpdate method and,

 processing user initiated operation to submit the one time code and upload the user's TEKs via the startKeysSubmission and fetchAndSubmitKeys functions.

The startKeysSubmission and fetchAndSubmitKeys run on a different thread from performExposureStatusUpdate and both threads can be executed in parallel.

The startKeysSubmission and performExposureStatusUpdate functions are able to modify the shared ExposureStatus variable without any concurrency control in place. This could result in one function overwriting the value set by another function before either function completes. It can result in the state of 'exposed' getting overwritten to 'diagnosed' and vice versa and prematurely stopping further processing of a diagnosis file upload or exposure matching.

The major side effect here is the uploading of an infected user's TEKs could be cancelled by a concurrent detection of a new exposure resulting in the user's TEK never getting uploaded to the server.

**Comment by obrien-j** [comment]
I imagine this is a fairly low likelihood scenario, but worth some 👀

**Comment by craigzour** [comment]
One possible solution I think could work (based on my past experiences) is to plug some kind of synchronous operation queue that will guarantee we finish executing one function before running the other. Will try to find a way to implement that in React Native.

**Comment by craigzour** [comment]
I made a PR. #1351

**Comment by timarney** [comment]
@craigzour wondering if we can write a unit test off current master to demo this issue.  That would help to validate any fix.

cc: @smcmurtry

**Comment by timarney** [comment]
Given we're mostly doing maintenance work at this point we won't be implementing any changes for this scenario.
