### ISSUE TITLE
You're all set displays after Bluetooth is turned off

### ISSUE THREAD

**Issue by jeffmaher** [cds-snc/covid-alert-app#916]
See this [Twitter thread](https://twitter.com/_NeilN/status/1286412495238856704). We'll reach out to the poster to get more details.

**Comment by phonedph1** [comment]
I reported this via beta feedback (via TestFlight) and the feedback survey as well - but I just did more testing and I think this is an Apple UI confusion as to what the bluetooth icon does in control center. 

If you toggle bluetooth off from control center it only turns into a white icon with the text saying "disconnecting bluetooth devices until tomorrow" and the app says OK (this apparently does NOT turn bluetooth off but disables NEW connections/pairings?)

If you actually go into settings -> bluetooth and turn it off the app updates to say bluetooth is off/alert is off.

**Comment by timarney** [comment]
> I think this is an Apple UI confusion as to what the bluetooth icon does in control center

Yes this is quite confusing, the control center disconnects devices from blue tooth it doesn't turn blue tooth off.

<img width="400" src="https://user-images.githubusercontent.com/62242/88667576-8eb06300-d0af-11ea-99be-5855afb76ae6.jpg">

**Comment by timarney** [comment]
Will wait for more details from the user (I responded on Twitter).


Ref: https://github.com/cds-snc/covid-alert-app/issues/231#issuecomment-650553004

**Comment by timarney** [comment]
**Response** 
https://twitter.com/_NeilN/status/1288100856160804865

> Control Center. Works as expected when turning off Bluetooth in Settings.

**Comment by emilykuret** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add to support content based on Beta feedback](https://trello.com/c/IdKbZuTE/284-add-to-support-content-based-on-beta-feedback)
