### ISSUE TITLE
Insufficient space message displayed after trying to download iOS v66 

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-alert-app#928]
iPhone 8 
27.1 GB of 64 GB Used space
Around 9:25pm last night (July 27), I attempted to update the iOS version 66 from the push notification on my locked screen.
Was directed to Testflight and clicked Update
It took longer than normal and then I got the following message: 
![IMG_1868](https://user-images.githubusercontent.com/65728700/88659077-7423bd00-d0a2-11ea-86e3-75ef9c9958a0.PNG)
![IMG_1870](https://user-images.githubusercontent.com/65728700/88659083-784fda80-d0a2-11ea-9d66-0d33f6a3a012.PNG)

I shouldn't have received this message.
Note that the app did install v66

**Comment by mtropper** [comment]
@mmiron-HC  do you have IOS 13.6 installed?

**Comment by mmiron-HC** [comment]
no still at 13.5.1

**Comment by timarney** [comment]
Going to close this as this was running a test build - will re-open as needed.
