### ISSUE TITLE
Menu headings are duplicated when I open the menu with finger scroll up

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-alert-app#929]
any device with app installed. now have v66 installed.
from the app, place your finger on the menu and slowly slide your finger up the screen towards the top to open the menu. Stop halfway - the heading on the menu appears twice slightly faded.
This wasn't like that before. 
![image](https://user-images.githubusercontent.com/65728700/88661618-cbc42780-d0a6-11ea-9aec-f3bdd02f8be9.png)

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-alert-app/pull/964

**Comment by emilykuret** [comment]
Could investigate getting rid of the two menu states by keeping instructional text (tap for menu) while the menu is open and closed.

**Comment by timarney** [comment]
Closing this - the adjustment we tried to make didn't work.  The animation / positioning of the fade is controlled by the bridge (native level code) so there's not quick solve. 

The menu will likely be re-visited in the future.
