### ISSUE TITLE
Turning Airplane mode on/off home screen very laggy between screens (android 10/8) v66

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-alert-app#930]
Android S8 and S10 
app v? july 27th
App installed and opened.
Your all set/No reporting in your area... message on Home screen
Turned Airplane mode on from quick access menu.
returned to app
Bluetooth is off message is displayed on Home screen 
Turned airplane mode off from quick access menu
returned to app
Bluetooth is off is still displayed, then it replaced with COVID Alert is Off message and eventually it goes back to your "happy" screen.
See video
iOS has a lag as well but nothing like this.

[IMG_1864.zip](https://github.com/cds-snc/covid-alert-app/files/4988158/IMG_1864.zip)

**Comment by emilykuret** [comment]
Closed - will retest and reopen as needed.
