### ISSUE TITLE
Android - turn on EN button is available before Play Services finishes updating

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-alert-app#931]
Adding this as an edge case and something to note for support issues around the "Turn on EN button" on the home screen not working.

- Factory reset Android phone
- Install Covid Alert
- OS Prompts that Play Services needs to be updated for Covid Alert to work
- Press to update Play Services (updating...)
- Onboard into the App
- Receive message saying EN is off -> button shows to turn on -> button doesn't do anything 
- Close the app 
- Play services finishes update
- Open app -> EN prompt to turn on 
- The app at this point ends up in the normal state

In this case the button would end up working after Play Services fully updates.

**Comment by emilykuret** [comment]
Added to the backlog under "Create more detailed error messaging".
