### ISSUE TITLE
iOS ver 66 - When in airplane mode the 'COVID Alert is offline' message is not displayed

### ISSUE THREAD

**Issue by ndolter** [cds-snc/covid-alert-app#932]
iOS XR= ver 66
Test case # 39

Steps:
1. Make sure your device is in airplane mode, open the app and from the Home screen:
- iPhone: Verify that 'COVID Alert is offline' is displayed and COVID Alert status is Active (since BT is on): **Fail** - 'Upload random codes' is displayed instead 
- Android: Verify that 'COVID Alert is off' is displayed and COVID Alert status is Off (turning on airplane mode automatically turns off BT): Pass on ver 7 & 8

**Comment by timarney** [comment]
When you're in Airplane mode are you turning off WiFi?

On the Bluetooth end believe this is the issue if your using the Control Center

https://support.apple.com/en-ca/HT208086

<img width="600" alt="Screen Shot 2020-07-28 at 12 57 21 PM" src="https://user-images.githubusercontent.com/62242/88696977-ef509780-d0d1-11ea-874e-74b54e3eda4f.png">

ref: https://github.com/cds-snc/covid-alert-app/issues/916

**Comment by ndolter** [comment]
No, I'm not turning off Wifi

**Comment by phonedph1** [comment]
Can't reproduce with airplane mode from control center on iphone 7 (13.6). Instantly shows bluetooth is off message. I can toggle it off in-app and it changes by the time I leave control center (the main menu changes while in control center and the "COVID Alert is off" updates right away).

This is on ver 67.

**Comment by ndolter** [comment]
Can you also try turning it off from Settings instead?

**Comment by phonedph1** [comment]
For me airplane mode from settings does the same as from control center in terms of what the app says (bluetooth off, alert is off)

**Comment by ndolter** [comment]
Do you have an XR you can try the test from?

**Comment by emilykuret** [comment]
Closed - will reopen as needed.
