### ISSUE TITLE
Error messages on key claim and key upload

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-alert-app#948]
Currently the code is issuing the same error message for key claim errors:

https://github.com/cds-snc/covid-alert-app/blob/31dd079e4069828bbd14ce5090bd3345ca148322/src/screens/datasharing/DataSharing.tsx#L26-L28

and similar for upload errors

https://github.com/cds-snc/covid-alert-app/blob/31dd079e4069828bbd14ce5090bd3345ca148322/src/screens/datasharing/DataSharing.tsx#L33-L36

This does not take into account some of the more common potential scenarios such as not being able to reach the server because of network issues, expired keys on the server, or potentially other edge cases.

The server will return a number of different error codes based on various scenarios:

https://github.com/cds-snc/covid-alert-app/blob/31dd079e4069828bbd14ce5090bd3345ca148322/src/services/BackendService/covidshield/covidshield.proto#L29-L35

and 

https://github.com/cds-snc/covid-alert-app/blob/31dd079e4069828bbd14ce5090bd3345ca148322/src/services/BackendService/covidshield/covidshield.proto#L77-L94

that could be used for more informative error codes.

**Comment by timarney** [comment]
cc: @smcmurtry @katewilhelm 

Let's get some 👀  on this when we can - more granular error messages :)

**Comment by obrien-j** [comment]
At a minimum, heads up, server team is setting an SLO of 80% uptime. Y'all have been warned. ;)
