### ISSUE TITLE
Prompt for exposure logging not showing up and not in setting either. 

### ISSUE THREAD

**Issue by brevanbabbar** [cds-snc/covid-alert-app#977]
When I first download the app and it says you’ll be asked to accept exposure login nothing shows up. When I go into exposure logging settings in the health privacy area says not available in your region and I am in Ontario.

**Comment by obrien-j** [comment]
Hey @brevanbabbar,

Could you answer the two subheadings below to help the team triage the issue accordingly.

# Steps to reproduce

> Sequential steps (1., 2., 3., ...) that describe how to reproduce the bug. This will help a developer experience what the user experienced so that they can debug it.

# Environment

> What kind of device was the bug experienced with. This would include device, version of the operating system (i.e. iOS or Android), and any other environmental details that might be relevant.

**Comment by emilykuret** [comment]
Adding this to another open issue.
