### ISSUE TITLE
Android "Retrieve Running Apps" GET_TASKS Permission - Clarify and Document

### ISSUE THREAD

**Issue by andrew-from-toronto** [cds-snc/covid-alert-app#979]
The Android app is requesting the GET_TASKS permission which results in a permission being listed on the Play store that the app will "retrieve running apps". This can be scary for users who are more concious of the permissions being requested. I tracked down this permission to the react-native-background-fetch package in use for background refreshing of exposure statuses. It would be good to both a) try to eliminate this permission in the manifest given that it is now deprecated and shouldn't be necessary per https://github.com/transistorsoft/react-native-background-fetch/issues/182 and b) in the meantime document what the permission is for, possibly even in the play store description.

**Comment by timarney** [comment]
Thanks @andrew-from-toronto 

I'll flag this issue back to the team.

cc: @emilykuret ☝️

**Comment by emilykuret** [comment]
Team is currently triaging.

**Comment by fredvb** [comment]
We should really find a way to eliminate this permissions if possible, until then document it. But it should be high on the list of things to get around.

**Comment by timarney** [comment]
Pulling out a couple of comments in the thread:

<hr>

<img width="700" alt="68747470733a2f2f646c2e64726f70626f782e636f6d2f732f676477346a396531316d7073776c6d2f53637265656e73686f74253230323031392d31302d313725323030382e33332e35342e706e673f646c3d31" src="https://user-images.githubusercontent.com/62242/96589818-46ba6a00-12b3-11eb-8e88-2b0f2ace580a.png">

> that's exactly what the plugin uses it for: to determine if the MainActivity is alive or not, so that it knows when to fire Headless events.

> That's all the plugin needs it for: the caller's own tasks.

<hr>
Also noting: 

https://github.com/transistorsoft/react-native-background-fetch/issues/182#issuecomment-653260870

**Comment by timarney** [comment]
Closing this and will take it back to the support team for further documentation.
