### ISSUE TITLE
iOS 14 beta - ExposureNotification isn’t currently available

### ISSUE THREAD

**Issue by madelive** [cds-snc/covid-alert-app#981]
# Summary

iOS Beta 14 disables contact tracing. Consider restricting the release versions in iTunes Store (if you can do that) to <14.0.

**Comment by timarney** [comment]
Thank you for reporting - we are aware. We'll see if there's anything further we can do on our end.

In the meantime, adding the release notes here for reference. 

###  iOS 14 beta release notes:

> Known Issues
ExposureNotification isn’t currently available in iOS 14 beta. Use iOS 13.6 beta to preview the latest functionality. (64433241)

https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes#ExposureNotification

<img width="500" alt="Screen Shot 2020-07-31 at 1 47 37 PM" src="https://user-images.githubusercontent.com/62242/89100166-08539400-d3c3-11ea-85c9-36297f80c671.png">

**Comment by jpeng06** [comment]
exposure API is now available in developer beta 4, should be available to public beta in next few days

**Comment by desmond-wang** [comment]
ios14beta4 is available, however it requires `ENDeveloperRegion` and `ENAPIVersion`
The link: [Apple COVID-19 guide ](https://developer.apple.com/documentation/exposurenotification) 
Otherwise, it just shows <no loc> error under settings-Exposure notification-Exposure logging-exposure checks. 
![F14E7781-D3DE-45FE-9C52-EEB009856AE5](https://user-images.githubusercontent.com/19340532/89438515-ea659680-d716-11ea-9357-f472adf51701.png)

**Comment by timarney** [comment]
Updated screens testing with PR  https://github.com/cds-snc/covid-alert-app/pull/1005 merged 

<img width="300" src="https://user-images.githubusercontent.com/62242/89585970-d308d500-d80c-11ea-96f8-5854f28e309a.png" />

<img width="300" src="https://user-images.githubusercontent.com/62242/89586000-e5830e80-d80c-11ea-91d8-af7afdd17204.png" />

We're still seeing the <no loc> "error" - we're told this is a known issue for the beta on the iOS end.
<img width="300" src="https://user-images.githubusercontent.com/62242/89586038-f29ffd80-d80c-11ea-84ed-aa85a3476aa7.png" />

**Comment by desmond-wang** [comment]
Does that mean app in ios14beta4 is working behind the scenes.  It just not able to check the log by user? Or iOS14 need to fix in order to work with the app?

**Comment by timarney** [comment]
> Does that mean app in ios14beta4 is working behind the scenes.

We're told with that PR in the API should function normally 

>  It just not able to check the log by user

I believe this is correct

**Comment by desmond-wang** [comment]
Thank you so much for you guys quick support for ios14 even as an beta software.

**Comment by lexcyn** [comment]
Yes thanks a lot! There are 10's of us that are running iOS beta here in Ontario who use this app ;)

**Comment by timarney** [comment]
FYI - iOS v1.0.3 (74) been rolled out and has the updates in it.

**Comment by drofmab** [comment]
I’m running v1.0.3 on iOS 14 beta 4, and I still see the <no loc> error documented in the screen shot above.

**Comment by timarney** [comment]
@drofmab thanks for noting.   That error is at the iOS framework level vs the app itself.

I mention that error above https://github.com/cds-snc/covid-alert-app/issues/981#issuecomment-670209510 but it's buried in that comment.  

Hopefully it's fixed soon as it's causing a lot of confusion.

<img width="690" alt="Screen Shot 2020-08-12 at 7 44 22 AM" src="https://user-images.githubusercontent.com/62242/90011479-a838d980-dc6f-11ea-8911-ca1f4a64a622.png">

**Comment by drofmab** [comment]
(I read that as "thanks for nothing"😉)

I'm glad I submitted an iOS issue in the beta feedback app, then. Thanks!

**Comment by timarney** [comment]
> I submitted an iOS issue in the beta feedback app

Perfect :)

**Comment by emilykuret** [comment]
Working with Apple on this - will reopen if needed.
