### ISSUE TITLE
Network traffic pattern can reveal infected people

### ISSUE THREAD

**Issue by uhengart** [cds-snc/covid-alert-app#986]
Assume somebody is monitoring the network traffic between a smartphone running the COVID Alert app and the key server that receives the diagnosis keys of infected people. This network monitor could be the smartphone user's ISP or cellphone provider, Amazon hosting the key server, or some random router between the two. The user gets infected and uploads their diagnosis keys. The network monitor can infer from the existence of this traffic (if the key server is used only for upload of diagnosis keys) or from the pattern of this traffic (if the same key server is used for both upload and download) that an upload of diagnosis keys is taking place. The network monitor now knows that the IP address associated with the source of the upload belongs to an infected person. Mapping the IP address to this person would be straightforward for an ISP or cellphone provider.

How does COVID Alert defend against this privacy leak? 

A possible defense is to have the app once in a while create upload requests with fake diagnosis keys such that network monitors cannot distinguish the requests from upload requests with real diagnosis keys. This approach is implemented in the Swiss exposure notification app and is going to be implemented in the German one.

**Comment by obrien-j** [comment]
Thanks @uhengart ,

We already have an active ticket or two for this in the server side of things, but didn't create an equivalent one in the app's repo.

linking: https://github.com/cds-snc/covid-alert-server/issues/100 and https://github.com/cds-snc/covid-alert-server/issues/185

I'll leave this ticket open here for tracking state and to hopefully minimize duplicate requests for this functionality.

I can't commit to timelines, but our plan is to implement a system similar to what Italy has in place, after a thorough analysis of their implementation.

**Comment by uhengart** [comment]
@obrien-j, thanks for the quick response. 

Has this privacy vulnerability been brought to the attention of the OPC, IPC Ontario, and Health Canada? I see no mention in their privacy reviews ([OPC](https://priv.gc.ca/en/privacy-topics/health-genetic-and-other-body-information/health-emergencies/rev_covid-app/), [IPC](https://www.ipc.on.ca/wp-content/uploads/2020/07/2020-07-30-ltr-michael-maddock-re-ipc-recommendations-to-the-government-of-ontario-regarding-covid-alert.pdf), [Health Canada](https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19/covid-alert/privacy-policy/assessment.html)).

If not, please do so asap and cc [me](https://cs.uwaterloo.ca/~uhengart) in the communication. Thanks.

**Comment by obrien-j** [comment]
@uhengart, sorry for the delayed response, long weekend caught up to me.

Your description of the issue around traffic analysis is inline with our own internal documentation regarding this risk. As noted in the linked github issues, this is something that we have been aware of since the start of our efforts on the project, and is one that we continue to work towards resolving. 

We discussed this issue with HC privacy and OPC, and continue to work with them as we decide on our approach for addressing the issue.

We'd be happy to discuss the technical implications of this with you further, and keep you apprised of our plans for remediation if you would like to participate.

**Comment by timarney** [comment]
Going to close this and follow up in cds-snc/covid-alert-server#100 and cds-snc/covid-alert-server#185 as need be.
