### ISSUE TITLE
Fail to enable the app on Huawei P20 Pro

### ISSUE THREAD

**Issue by MatthewZMD** [cds-snc/covid-alert-app#993]
# Summary

Clicking on the button 'Enable COVID Alert' does nothing.

![Screenshot_20200804_125125_ca.gc.hcsc.canada.stopcovid.jpg](https://user-images.githubusercontent.com/12422335/89321626-3817cb80-d651-11ea-8576-32cd039fb64f.jpg)

# Steps to reproduce

After pressing 'Next' for all the info pages, and select 'Ontario' as the provence. Ensured both Bluetooth and Location are enabled. Clicking on the button 'Enable COVID Alert' does nothing.

# Environment

Huawei P20 Pro, Android 10

**Comment by andehwong** [comment]
This bug is also occurring on the Xiaomi Mi 6X.

**Comment by timarney** [comment]
Please add a screenshot here for what your seeing in the settings.

> Settings, then choose Google, then COVID-19 Exposure Notifications

You should see a screen like this.

<img width="300" src="https://user-images.githubusercontent.com/62242/89682451-c1830400-d8c4-11ea-8c4e-37a8880e1cbc.png">

**Comment by MatthewZMD** [comment]
@timarney I do not see a 'COVID-19 Exposure Notifications' section under `Settings -> Google`. Upon googling I find that it comes from a Google Play Services update but [most Android phones get this update. Some Huawei phones may not get the update.](https://support.google.com/android/answer/9888358?hl=en)

This is a serious issue for the new Huawei phone users, **however** it shouldn't affect me because Huawei P20 Pro came out in 2018, and the US ban came out in May 2019 affecting only the new models. 

My Google Play Services has version 20.26.14 (120408-320008519), please verify on your side on the version of Google rolling out the COVID-19 Exposure Notifications update, as I cannot access this information on my side.

**Comment by junzew** [comment]
@timarney The bug is also occurring on OPPO R11s. Android 8.1.0. Google play services version 20.26.14.
I ensured Bluetooth and Location settings are both turned on, but clicking "Enable COVID Alert' doesn't do anything.
Exposure Notifications settings under Settings->Google are disabled even after installing the app.
![image](https://user-images.githubusercontent.com/17218080/89743632-caf1a500-da59-11ea-8740-b699d25bdd2a.png)

**Comment by MatthewZMD** [comment]
@junzew can you show me a screenshot of your System->Google, as I cannot even find the Exposure Notification button with the same version as you.

**Comment by junzew** [comment]
@MatthewZMD I had to install a [third-party launcher](https://play.google.com/store/apps/details?id=com.pentasa.gamemn02.googlesettingsshortcut) to access Google settings because my phone runs a custom version of Android. It might also be the case for your Huawei phone.

**Comment by emilykuret** [comment]
Thanks for the feedback - we have captured this into our feedback tracker.
